// Sparkle: the app updates itself from an EdDSA-signed appcast generated by
// the release workflow, with no FSL-run server anywhere in the path
// (docs/product/desktop-app-plan.md, "Updates"; docs/ops/releases.md).
//
// The feed URL and the public key are Info.plist keys, not literals here:
//   SUFeedURL     https://github.com/foldedspacelabs/metistry/releases/latest/download/appcast.xml
//   SUPublicEDKey the key generated 2026-09-09, also in
//                 ops/release/runtime-versions.env as SPARKLE_PUBLIC_ED_KEY
// Sparkle reads both itself. Keeping them in one place means the app cannot
// disagree with the workflow that signs the feed.
//
// The other half of the story is the product runtime, which does NOT update
// through Sparkle: that is `metistry update` in release mode (pinned artifacts,
// migrations under the advisory lock). Two channels, both signed, on purpose.

#if os(macOS)
import Foundation
import Sparkle
import SwiftUI

@MainActor
final class UpdaterController {
    let controller: SPUStandardUpdaterController

    init() {
        // startingUpdater: true — Sparkle schedules its own background checks
        // from the plist's SUScheduledCheckInterval. No delegate yet: the
        // default behaviour (ask on first launch, then check daily) is what the
        // plan describes, and a delegate that adds nothing is a delegate to
        // maintain for years.
        controller = SPUStandardUpdaterController(startingUpdater: true, updaterDelegate: nil, userDriverDelegate: nil)
    }

    var feedURL: String {
        Bundle.main.object(forInfoDictionaryKey: "SUFeedURL") as? String ?? "(no SUFeedURL in Info.plist)"
    }

    var canCheck: Bool { controller.updater.canCheckForUpdates }

    func checkForUpdates() {
        controller.updater.checkForUpdates()
    }
}

/// The "Check for Updates…" item, in the app menu where macOS users look for it.
struct CheckForUpdatesCommand: View {
    let updater: UpdaterController

    var body: some View {
        Button("Check for Updates…") { updater.checkForUpdates() }
            .disabled(!updater.canCheck)
    }
}
#endif
