export {
  manifestSchema,
  validateManifest,
  targetManifest,
  dataPolicySchema,
  type Manifest,
  type ManifestResult,
  type TargetManifest,
  type DataPolicy,
  agentManifest,
  CREW_TOOL_GROUPS,
  CREW_GROUP_ALIASES,
  CREW_NEVER_TOOLS,
  CREW_MODELS,
  crewGroupOf,
  crewToolsFor,
  type AgentManifest,
  type CrewToolGroup,
} from "./manifest.js";
export { checkResultSchema, runCheck, type CheckResult, type Checkable } from "./check.js";
export { errorEnvelope, statusFor, type ErrorCode, type ErrorEnvelope } from "./errors.js";
export { requireEnv, optionalEnv, intEnv } from "./config.js";
export {
  DEPLOYMENT_FILENAME,
  DEPLOYMENT_SHAPES,
  SHAPED_SERVICES,
  HOST_SERVICES,
  ALL_SERVICES,
  DEFAULT_DEPLOYMENT,
  CONTAINER_HOSTNAMES,
  deploymentSchema,
  serviceOverrideSchema,
  parseDeployment,
  overlayDeployment,
  shapeOf,
  enabled,
  servicePlan,
  usesCompose,
  resolveUrl,
  type Deployment,
  type DeploymentShape,
  type ServiceName,
  type ServiceOverride,
  type UrlContext,
  type Vantage,
} from "./deployment.js";
export {
  SUPERVISOR_LABEL,
  SUPERVISOR_SERVICE,
  SUPERVISOR_CONFIG_FILENAME,
  SUPERVISOR_SOCKET_FILENAME,
  RESTART_BACKOFF_MS,
  RESTART_BACKOFF_MAX_MS,
  RESTART_HEALTHY_MS,
  CRASH_LOOP_RESTARTS,
  CRASH_LOOP_WINDOW_MS,
  STOP_GRACE_MS,
  READY_TIMEOUT_MS,
  CONTROL_OPS,
  CONTROL_UNAUTHORIZED,
  childSpecSchema,
  readyProbeSchema,
  supervisorConfigSchema,
  controlRequestSchema,
  parseSupervisorConfig,
  type ChildSpec,
  type ChildSpecInput,
  type ChildState,
  type ChildStatus,
  type ControlOp,
  type ControlRequest,
  type ControlResponse,
  type ReadyProbe,
  type SupervisorConfig,
  type SupervisorConfigInput,
} from "./supervisor.js";
export { scheduleToSeconds } from "./schedule.js";
export {
  EFFORTS,
  DEFAULT_TIER,
  ROUTINE_TIER,
  tierSchema,
  tiersSchema,
  resolveTier,
  parseTiers,
  type Effort,
  type Tier,
  type TierMap,
  type ResolvedTier,
} from "./tiers.js";
export { rollSession, type RollResult } from "./session-roll.js";
export {
  REDACTED,
  redactSecrets,
  scrubModelOutput,
  containsRedactedPlaceholder,
} from "./redact.js";
export { parseBearer, tokenEquals, authorized, tokenHash, mintToken } from "./auth.js";
export { sanitizeForAgent } from "./sanitize.js";
export { parseDecisionBlock, type DecisionBlock } from "./decision-block.js";
export {
  startRun,
  finishRun,
  withRun,
  type RunExecutor,
  type RunStart,
  type RunFinish,
} from "./runs.js";
export {
  ensureProject,
  getProject,
  toProjectRow,
  PROJECT_SLUG_RE,
  PROJECT_MODES,
  PROJECT_COLS,
  DEFAULT_MAX_OPEN_BUNDLES,
  type ProjectExecutor,
  type ProjectMode,
  type ProjectRow,
} from "./projects.js";
export {
  chunkMarkdown,
  vectorLiteral,
  EmbedClient,
  EmbedUnavailableError,
  CHUNK_TARGET_CHARS,
  CHUNK_OVERLAP_CHARS,
  EMBED_DEFAULT_URL,
  EMBED_DEFAULT_MODEL,
  EMBED_DEFAULT_DIM,
  EMBED_DEFAULT_BATCH,
  type Chunk,
  type ChunkOptions,
  type EmbedClientOptions,
  type FetchLike,
} from "./embed.js";
export {
  summarizeTranscript,
  renderSessionNote,
  renderSessionBody,
  sessionTitle,
  idempotencyKey,
  formatDuration,
  repoNameFromPath,
  decodeProjectDir,
  textOf,
  clip,
  MAX_FILES,
  FIRST_PROMPT_CHARS,
  LAST_MESSAGE_CHARS,
  type SessionSummary,
} from "./session-summary.js";
