export {
  manifestSchema,
  validateManifest,
  targetManifest,
  dataPolicySchema,
  requirementsSchema,
  type Requirements,
  type Manifest,
  type ManifestResult,
  type TargetManifest,
  type DataPolicy,
  agentManifest,
  CREW_TOOL_GROUPS,
  CREW_GROUP_ALIASES,
  CREW_NEVER_TOOLS,
  CREW_MODELS,
  crewGroupOf,
  crewToolsFor,
  type AgentManifest,
  type CrewToolGroup,
} from "./manifest.js";
export {
  ACTION_KINDS,
  ACTION_MODES,
  AUTONOMY_LEVELS,
  DEFAULT_AUTONOMY_LEVEL,
  LEVEL_CEILING,
  ACTION_DEFAULTS,
  ACTION_TASK_PATCH_FIELDS,
  ACTION_TASK_STATUSES,
  actionSchema,
  actionTableSchema,
  parseAction,
  actionWorkId,
  describeAction,
  effectiveActions,
  admitsAnyAction,
  autonomyWidenings,
  modeRank,
  levelRank,
  type Action,
  type ActionKind,
  type ActionMode,
  type ActionAutonomy,
  type AutonomyLevel,
} from "./actions.js";
export { checkResultSchema, runCheck, type CheckResult, type Checkable } from "./check.js";
export {
  INSTANCE_LAYOUT,
  INSTANCE_CONFIG_DIRS,
  INSTANCE_GITIGNORE,
  INSTANCE_GITIGNORE_LINES,
  LEGACY_INSTANCE_LAYOUT,
  LEGACY_MACHINERY_ROOTS,
  LEGACY_VAULT_DIR,
  NON_VAULT_ROOTS,
  PROTECTED_ROOT_FILES,
  SEED_DIR,
  VAULT_ROOT_AREA,
  detectLayout,
  instanceFile,
  instancePath,
  instanceStatePath,
  isProtectedPath,
  isVaultPath,
  metistryPath,
  overlayFiles,
  overlayFilesFromEnv,
  resolveInstanceLayout,
  seedFile,
  statePath,
  type InstanceLayoutShape,
  type InstancePathKey,
  type ResolvedInstanceLayout,
} from "./instance-layout.js";
export {
  checkStdioConformance,
  isJsonLineFrame,
  renderStdoutViolations,
  stdoutViolations,
  type StdioConformanceOptions,
  type StdioConformanceResult,
  type StdoutViolation,
} from "./stdio-conformance.js";
export { errorEnvelope, statusFor, type ErrorCode, type ErrorEnvelope } from "./errors.js";
export { requireEnv, optionalEnv, intEnv } from "./config.js";
export {
  DEPLOYMENT_FILENAME,
  DEPLOYMENT_SHAPES,
  SHAPED_SERVICES,
  HOST_SERVICES,
  ALL_SERVICES,
  DEFAULT_DEPLOYMENT,
  CONTAINER_HOSTNAMES,
  deploymentSchema,
  serviceOverrideSchema,
  parseDeployment,
  overlayDeployment,
  keepAwakeOf,
  shapeOf,
  enabled,
  servicePlan,
  usesCompose,
  resolveUrl,
  type Deployment,
  type DeploymentShape,
  type ServiceName,
  type ServiceOverride,
  type UrlContext,
  type Vantage,
} from "./deployment.js";
export {
  KEEP_AWAKE_VALUES,
  KEEP_AWAKE_DEFAULT,
  KEEP_AWAKE_RECOMMENDED,
  KEEP_AWAKE_CHOICES,
  KEEP_AWAKE_ENV,
  KEEP_AWAKE_KIND,
  KEEP_AWAKE_STATE_FILENAME,
  KEEP_AWAKE_CUTOFF_FACTOR,
  LID_CLOSED_NOT_AVAILABLE,
  POWER_SOURCES,
  keepAwakeChoice,
  parseKeepAwake,
  parsePowerSource,
  powerSourceLabel,
  onWallPower,
  shouldHold,
  describeKeepAwake,
  keepAwakeStateSchema,
  keepAwakeCutoffSchema,
  parseKeepAwakeState,
  cutoffIsAFinding,
  humanGap,
  type KeepAwake,
  type KeepAwakeChoice,
  type KeepAwakeCutoff,
  type KeepAwakeState,
  type PowerSource,
} from "./power.js";
export {
  SUPERVISOR_LABEL,
  SUPERVISOR_SERVICE,
  SUPERVISOR_CONFIG_FILENAME,
  SUPERVISOR_SOCKET_FILENAME,
  RESTART_BACKOFF_MS,
  RESTART_BACKOFF_MAX_MS,
  RESTART_HEALTHY_MS,
  CRASH_LOOP_RESTARTS,
  CRASH_LOOP_WINDOW_MS,
  STOP_GRACE_MS,
  READY_TIMEOUT_MS,
  CONTROL_OPS,
  CONTROL_UNAUTHORIZED,
  childSpecSchema,
  readyProbeSchema,
  supervisorConfigSchema,
  controlRequestSchema,
  parseSupervisorConfig,
  type ChildSpec,
  type ChildSpecInput,
  type ChildState,
  type ChildStatus,
  type ControlOp,
  type ControlRequest,
  type ControlResponse,
  type ReadyProbe,
  type SupervisorConfig,
  type SupervisorConfigInput,
} from "./supervisor.js";
export { scheduleToSeconds } from "./schedule.js";
export {
  COST_SOURCES,
  DEFAULT_CACHE_READ_MULTIPLIER,
  DEFAULT_CACHE_WRITE_MULTIPLIER,
  usageFromResponse,
  costOf,
  unpricedNote,
  type CallCost,
  type CallUsage,
  type CostSource,
} from "./cost.js";
export {
  BUDGET_EXCEEDED,
  BUDGET_WARN_FRACTION,
  BUDGET_WINDOWS,
  NO_SPEND,
  SPEND_QUERY,
  checkBudgets,
  budgetRefusalMessage,
  budgetWarningMessage,
  budgetWindowKey,
  budgetMiss,
  spentFrom,
  type BudgetCheckInput,
  type BudgetHit,
  type BudgetVerdict,
  type BudgetWindow,
  type SpendRow,
  type Spent,
} from "./budget.js";
export {
  COMPUTE_FILENAME,
  COMPUTE_FILES_DEFAULT,
  RULES_FILES_DEFAULT,
  PROVIDER_KINDS,
  LOCALITIES,
  CACHING_MODES,
  DEFAULT_CACHING,
  BUDGET_ACTIONS,
  DEFAULT_BUDGET_ACTION,
  SECRET_NAME_RE,
  PROVIDER_NAME_RE,
  providerSchema,
  assignmentSchema,
  assignmentsSchema,
  budgetSchema,
  budgetsSchema,
  computeSchema,
  engineStatus,
  engineConfigured,
  engineKindFor,
  crossKindRefusal,
  serveSchema,
  shadowSchema,
  resolveShadow,
  SERVE_RUNTIMES,
  servedProviders,
  collectorProviderIssue,
  firstOnMachineBaseUrl,
  modelRefIssue,
  parseModelRef,
  parseCompute,
  validateCompute,
  emptyCompute,
  assignsNothing,
  resolveAssignment,
  computeTiers,
  computePaths,
  loadCompute,
  startComputeWatch,
  ComputeStore,
  type Assignment,
  type Assignments,
  type Budget,
  type BudgetAction,
  type CachingMode,
  type Budgets,
  type Compute,
  type CrossKindRefusal,
  type EngineKind,
  type EngineStatus,
  type ComputeReload,
  type ComputeResult,
  type ComputeWatch,
  type ComputeWatchOptions,
  type LoadedCompute,
  type Locality,
  type ModelRef,
  type Provider,
  type ProviderKind,
  type ReadFile,
  type ResolvedAssignment,
  type ResolvedShadow,
  type Serve,
  type Shadow,
  type LlamaServe,
  type ServeRuntime,
  type WatchSeam,
} from "./compute.js";
export {
  EFFORTS,
  DEFAULT_TIER,
  ROUTINE_TIER,
  tierSchema,
  tiersSchema,
  resolveTier,
  parseTiers,
  type Effort,
  type Tier,
  type TierMap,
  type ResolvedTier,
} from "./tiers.js";
export {
  INSTANCES_FILENAME,
  CAPABILITIES,
  AGENT_NAME_RE,
  INSTANCE_ID_RE,
  QUALIFIED_AGENT_RE,
  normalizeCapabilities,
  qualifyAgentId,
  qualifyIfPossible,
  parseAgentId,
  instanceEntrySchema,
  instancesSchema,
  emptyInstances,
  validateInstances,
  parseInstances,
  findInstance,
  type Capability,
  type InstanceEntry,
  type Instances,
  type InstancesResult,
} from "./instances.js";
export { rollSession, type RollResult } from "./session-roll.js";
export {
  REDACTED,
  redactSecrets,
  scrubModelOutput,
  containsRedactedPlaceholder,
} from "./redact.js";
export { parseBearer, tokenEquals, authorized, tokenHash, mintToken } from "./auth.js";
export { sanitizeForAgent } from "./sanitize.js";
export { parseDecisionBlock, SKIP_FEEDBACK, type DecisionBlock } from "./decision-block.js";
export {
  startRun,
  finishRun,
  withRun,
  type RunExecutor,
  type RunStart,
  type RunFinish,
} from "./runs.js";
export {
  DEFAULT_MAX_STREAK,
  DEFAULT_ALERT_DEDUPE_HOURS,
  RUNNER_KIND,
  SKIPPED_STREAK,
  PREFLIGHT_FAILED,
  SCHEDULED_KINDS,
  normalizeError,
  errorSignature,
  signatureTag,
  failureStreaks,
  streakFor,
  shouldAlert,
  type ComponentStreak,
  type AlertGate,
} from "./failure.js";
export {
  DEFAULT_PREFLIGHT_TIMEOUT_MS,
  NO_REQUIREMENTS,
  requirementsOf,
  preflight,
  blockedConfigMessage,
  type PreflightMiss,
  type PreflightOptions,
  type PreflightResult,
} from "./preflight.js";
export {
  ensureProject,
  getProject,
  toProjectRow,
  PROJECT_SLUG_RE,
  PROJECT_MODES,
  PROJECT_COLS,
  DEFAULT_MAX_OPEN_BUNDLES,
  type ProjectExecutor,
  type ProjectMode,
  type ProjectRow,
} from "./projects.js";
export {
  chunkMarkdown,
  vectorLiteral,
  EmbedClient,
  EmbedUnavailableError,
  CHUNK_TARGET_CHARS,
  CHUNK_OVERLAP_CHARS,
  EMBED_DEFAULT_URL,
  EMBED_DEFAULT_MODEL,
  EMBED_DEFAULT_DIM,
  EMBED_DEFAULT_BATCH,
  LOCAL_MODEL_URL_VAR,
  OLLAMA_URL_VAR,
  apiRootOf,
  resolveLocalModelUrl,
  type Chunk,
  type ChunkOptions,
  type EmbedClientOptions,
  type FetchLike,
  type LocalModelUrl,
} from "./embed.js";
export {
  summarizeTranscript,
  renderSessionNote,
  renderSessionBody,
  sessionTitle,
  idempotencyKey,
  formatDuration,
  repoNameFromPath,
  decodeProjectDir,
  textOf,
  clip,
  MAX_FILES,
  FIRST_PROMPT_CHARS,
  LAST_MESSAGE_CHARS,
  type SessionSummary,
} from "./session-summary.js";
