export {
  manifestSchema,
  validateManifest,
  targetManifest,
  dataPolicySchema,
  requirementsSchema,
  type Requirements,
  type Manifest,
  type ManifestResult,
  type TargetManifest,
  type DataPolicy,
  agentManifest,
  CREW_TOOL_GROUPS,
  CREW_GROUP_ALIASES,
  CREW_NEVER_TOOLS,
  CREW_MODELS,
  CREW_FRONTMATTER,
  MAX_CREW_PROMPT_CHARS,
  SAME_AS_ASSISTANT,
  crewGroupOf,
  crewModelIssue,
  crewToolsFor,
  isLegacyCrewModel,
  parseCrewDefinition,
  type AgentManifest,
  type CrewModelAlias,
  type ParsedCrewDefinition,
  type CrewToolGroup,
  connectionTypeManifest,
  MANIFEST_SCHEMA_VERSION,
  schemaVersionIssue,
  type ConnectionTypeManifest,
  type ManifestType,
  providerManifest,
  type ProviderManifest,
  CONFIG_FIELD_KINDS,
  PRESENTS_AS,
  configFieldSchema,
  configValueIssue,
  raiseRuleSchema,
  type ConfigField,
  type ConfigFieldKind,
  type PresentsAs,
  type RaiseRule,
} from "./manifest.js";
export {
  AUTH_SCHEMES,
  CONNECTION_CAPABILITIES,
  CONNECTION_TYPES,
  CUSTOM_PROVIDER,
  DEFAULT_TOOL_MODE,
  FIELD_KINDS,
  NATIVE_REACH,
  OAUTH_REDIRECTS,
  REACH_CLASSES,
  REFUSED_CAPABILITIES,
  TOOL_GROUPS,
  TOOL_MODES,
  capabilityIssue,
  connectionFieldSchema,
  connectionFileSchema,
  connectionImplementationSchema,
  connectionIssues,
  httpAuthSchema,
  oauthClientSchema,
  reachClassOf,
  reachSchema,
  templateRefs,
  validateConnectionFile,
  type AuthScheme,
  type ConnectionCapability,
  type ConnectionField,
  type ConnectionFile,
  type ConnectionFileResult,
  type ConnectionImplementation,
  type ConnectionType,
  type FieldKind,
  type HttpAuth,
  type OAuthClient,
  type OAuthRedirect,
  type Reach,
  type ReachClass,
  type ToolGroup,
  type ToolMode,
} from "./connections.js";
export {
  EXTENSION_MODES,
  MANIFEST_FILE,
  REGISTRY_KINDS,
  UNIT_ORIGINS,
  buildRegistry,
  describeExtensions,
  extensionsDirFor,
  extensionsDirFromEnv,
  isRegistryKind,
  joinCode,
  unitCode,
  type CodedUnit,
  type MissingCode,
  kindHome,
  kindSources,
  loadKind,
  loadRegistry,
  manifestKind,
  readCandidates,
  unclaimedReason,
  type ExtensionEntry,
  type ExtensionMode,
  type KindRoots,
  type Registry,
  type RegistryKind,
  type RegistryKindName,
  type RegistryKindSpec,
  type RegistrySkip,
  type RegistrySource,
  type RegistryUnit,
  type UnitCandidate,
  type UnitOrigin,
} from "./registry.js";
export {
  CHOICE_ALPHABET,
  CHOICE_CODE_CEILING,
  CHOICE_MAX_OPTIONS,
  CHOICE_SERVERS,
  CHOICE_WIRE,
  CHOICE_WIRE_UNKNOWN,
  choiceBody,
  choiceConfidence,
  choicePlan,
  choiceServerOf,
  choiceWireFor,
  codesFor,
  readChoice,
  scoreChoiceOver,
  stageFor,
  type ChoiceCall,
  type ChoiceFetch,
  type ChoiceGroup,
  type ChoiceMessage,
  type ChoiceOption,
  type ChoiceReading,
  type ChoiceScored,
  type ChoiceServer,
  type ChoiceStage,
  type ChoiceWire,
  type TopLogprob,
} from "./choice.js";
export {
  DEFAULT_INTENT_PHRASING,
  INTENTS,
  INTENT_CODES,
  INTENT_GROUPS,
  INTENT_MAX_CHARS,
  INTENT_NAMES,
  INTENT_OPTIONS,
  INTENT_PHRASINGS,
  INTENT_UNSURE,
  INTENT_WITHIN_ONE_CALL,
  intentGuard,
  intentMessages,
  intentRulesSchema,
  intentStage,
  intentThreshold,
  isIntent,
  messageFacts,
  type Intent,
  type IntentGuard,
  type IntentPhrasing,
  type IntentPromptOptions,
  type IntentRules,
} from "./intent.js";
export {
  resolveOnMachineCall,
  scoreChoice,
  type ChoiceScore,
  type ModelAccess,
  type ResolvedOnMachineCall,
  type ScoreChoiceOptions,
} from "./score-choice.js";
export {
  COMPLEXITY,
  COMPLEXITY_NAMES,
  COMPLEXITY_OPTIONS,
  DEFAULT_OPERATION,
  POLICY_MODES,
  POLICY_TIMEOUT_DEFAULT_MS,
  POLICY_TIMEOUT_MAX_MS,
  POLICY_TIMEOUT_MIN_MS,
  ROUTE_OPERATIONS,
  RUNTIME_BOUNDS,
  boundDecision,
  complexityMessages,
  complexityStage,
  complexityValue,
  decide,
  intentValue,
  isComplexity,
  parseOperation,
  policyReads,
  scoreRouteFeatures,
  scorerTimeoutMs,
  tierTarget,
  validateRoutePolicy,
  type BoundedDecision,
  type BoundsContext,
  type Complexity,
  type ComplexityFeature,
  type FeatureRange,
  type IntentFeature,
  type ModelFeatureOutcome,
  type ModelFeatures,
  type ParsedOperation,
  type PolicyChoice,
  type PolicyContext,
  type PolicyDecision,
  type PolicyFeatures,
  type PolicyMode,
  type PolicyRow,
  type PolicyThen,
  type PolicyValidation,
  type PolicyWhen,
  type RouteOperation,
  type RouteOperationForm,
  type RoutePolicyConfig,
  type RouteScoreOptions,
  type RuntimeBound,
  type ScorerProvenance,
  type TierByComplexity,
  type TierTarget,
} from "./router-policy.js";
export {
  ACTION_KINDS,
  PROPOSABLE_ACTION_KINDS,
  isProposableActionKind,
  ACTION_KIND_CEILING,
  ceilingFor,
  CONFIRM_TOKEN_RE,
  mintConfirmToken,
  confirmTokenDigest,
  canonicalJson,
  connectionCallDigest,
  ACTION_MODES,
  AUTONOMY_LEVELS,
  DEFAULT_AUTONOMY_LEVEL,
  LEVEL_CEILING,
  ACTION_DEFAULTS,
  ACTION_TASK_PATCH_FIELDS,
  ACTION_TASK_STATUSES,
  actionSchema,
  actionTableSchema,
  parseAction,
  actionWorkId,
  describeAction,
  effectiveActions,
  effectiveActionsDetailed,
  admitsAnyAction,
  autonomyWidenings,
  modeRank,
  levelRank,
  type Action,
  type ActionKind,
  type ProposableActionKind,
  type ConnectionCallPayload,
  type ActionMode,
  type ActionAutonomy,
  type ActionSource,
  type EffectiveActionEntry,
  type AutonomyLevel,
} from "./actions.js";
export {
  ACTION_PERMISSION_CELLS,
  NO_SCOPE,
  NO_SUCH_PAGE,
  OWNER_SCOPE,
  PERMISSION_ASKS_MARK,
  PERMISSION_CONNECTION_MARK,
  PERMISSION_EMPTY_CELL,
  PERMISSION_RESOURCE_LABEL,
  TITLES_ONLY_LABEL,
  TOOL_PERMISSION_CELLS,
  WHOLE_VAULT_LABEL,
  describePermissions,
  permissionCellText,
  permissionEntryText,
  permissionProvenanceText,
  permissionRowText,
  type DescribePermissionsOptions,
  type PermissionCell,
  type PermissionCellEntries,
  type PermissionColumn,
  type PermissionConnection,
  type ToolPlacement,
  NO_SUCH_CONNECTION,
  REASONS,
  REFUSAL,
  RESOURCE_CLASSES,
  RULED_TOOLS,
  ROLES,
  ROLE_LABEL,
  SCOPE_REQUIRED,
  TIER_LABEL,
  allowedTools,
  areaOf,
  canSee,
  canSeeUnder,
  classify,
  describeScope,
  filterHits,
  filterPages,
  formatRefusal,
  grantedScope,
  INHERITED_QUERIES,
  INHERITED_TITLES,
  inheritGrants,
  may,
  mayListPath,
  mayReadPath,
  memberOfProject,
  notKnowledge,
  readableAreas,
  scopeRequired,
  sourceLabel,
  titlePrefixes,
  titlesOnly,
  underAreas,
  validKnowledgePath,
  type ConnectionDoor,
  type ConsoleDoor,
  type Decision,
  type GrantSource,
  type GrantEnvelope,
  type GrantTier,
  type InheritedReach,
  type KnowledgeDoor,
  type KnowledgeScope,
  type Needs,
  type Principal,
  type ProjectDoor,
  type ProjectGrant,
  type QueryDoor,
  type Reason,
  type Refusal,
  type RefusalEnvelope,
  type Resource,
  type ResourceClass,
  type Role,
  type Scope,
  type ScopeView,
  type Tell,
  type Verb,
} from "./access.js";
export {
  ACTOR_KINDS,
  ACTOR_OF_AGENT_KIND,
  ASSISTANT_AGENT_ID,
  ActorPermissionRefused,
  EMPTY_SCOPE,
  PERMISSION_RESOURCES,
  actorKindOf,
  crewCompute,
  crewPermissionRows,
  crewToolGroups,
  externalPermissionRows,
  resolveActor,
  scopeOfRegistryRow,
  type Actor,
  type ActorCompute,
  type ActorCrewSource,
  type ActorDefinition,
  type ActorGrantHistory,
  type ActorKind,
  type ActorLimits,
  type ActorPermissions,
  type ActorRegistryRow,
  type ActorSources,
  type ActorTools,
  type AgentRowKind,
  type AssistantActor,
  type AssistantDefinition,
  type AssistantIdentity,
  type CrewActor,
  type CrewActorDefinition,
  type CrewPermissionRow,
  type DefinitionFile,
  type ExternalActor,
  type ExternalPermissionRow,
  type ModelRefString,
  type PermissionEntry,
  type PermissionProvenance,
  type PermissionResource,
  type PermissionResourceKind,
  type PermissionRow,
  type ResolveActor,
} from "./actor.js";
export { checkResultSchema, runCheck, type CheckResult, type Checkable } from "./check.js";
export {
  AREA_PREFIX_RE,
  AREA_PREFIX_REFUSAL,
  INSTANCE_LAYOUT,
  INSTANCE_CONFIG_DIRS,
  INSTANCE_GITIGNORE,
  INSTANCE_GITIGNORE_LINES,
  JOURNAL_DIR,
  JOURNAL_MACHINE_DIRS,
  JOURNAL_ROUTINE_DIRS,
  journalRoutineOf,
  LEGACY_INSTANCE_LAYOUT,
  LEGACY_MACHINERY_ROOTS,
  LEGACY_VAULT_DIR,
  MAX_AREA_PREFIX_LEN,
  NON_VAULT_ROOTS,
  PROTECTED_ROOT_FILES,
  SEED_DIR,
  USER_OWNED_ROOTS,
  VAULT_ROOT_AREA,
  detectLayout,
  instanceFile,
  instancePath,
  instanceStatePath,
  isProtectedPath,
  isUserOwnedPath,
  isVaultPath,
  metistryPath,
  overlayFiles,
  overlayFilesFromEnv,
  resolveInstanceLayout,
  seedFile,
  statePath,
  validAgentAreaGrant,
  validAreaPrefix,
  type InstanceLayoutShape,
  type InstancePathKey,
  type ResolvedInstanceLayout,
} from "./instance-layout.js";
export {
  checkStdioConformance,
  isJsonLineFrame,
  renderStdoutViolations,
  stdoutViolations,
  type StdioConformanceOptions,
  type StdioConformanceResult,
  type StdoutViolation,
} from "./stdio-conformance.js";
export {
  API_VERSION,
  API_VERSION_HEADER,
  CLIENT_API,
  CLIENT_PRINCIPALS,
  CONFLICT_REASONS,
  IDEMPOTENCY,
  REACHES,
  REACH_PRINCIPALS,
  ROUTE_METHODS,
  isLocalRoute,
  localOnlyMessage,
  matchRoute,
  noRouteMessage,
  routeKey,
  servedRoute,
  type ClientPrincipal,
  type ClientRoute,
  type ConflictReason,
  type Idempotency,
  type ClientReach,
  type RouteMatch,
  type RouteMethod,
} from "./client-api.js";
export {
  EVENTS_CAPABILITY,
  EVENTS_ROUTE,
  EVENT_CATALOGUE,
  EVENT_REACH,
  EVENT_TYPES,
  VAULT_SYNC_STATES,
  isEventType,
  type ClientEvent,
  type EventDefinition,
  type EventPayloads,
  type EventType,
  type RunEvent,
  type VaultSyncState,
} from "./events.js";
export {
  PUSH_SCHEDULE_ENV,
  VAULT_SYNC_DEFAULT,
  VAULT_SYNC_MAX_SEC,
  VAULT_SYNC_MIN_SEC,
  VAULT_SYNC_RUN_KIND,
  describeVaultSync,
  intervalSeconds,
  overlayVaultSync,
  parsePullArg,
  parsePushArg,
  pushFromSchedule,
  pushOverrideNote,
  resolveVaultSync,
  vaultIntervalSchema,
  vaultPullSchema,
  vaultPushSchema,
  vaultStatusSchema,
  vaultSyncAttemptSchema,
  vaultSyncSchema,
  type ResolvedVaultSync,
  type VaultPull,
  type VaultPush,
  type VaultStatus,
  type VaultSyncAttempt,
  type VaultSyncBlock,
  type VaultSyncPolicy,
} from "./vault-sync.js";
export { errorEnvelope, statusFor, type ErrorCode, type ErrorEnvelope } from "./errors.js";
export { requireEnv, optionalEnv, intEnv } from "./config.js";
export {
  DEPLOYMENT_FILENAME,
  DEPLOYMENT_SHAPES,
  SHAPED_SERVICES,
  HOST_SERVICES,
  ALL_SERVICES,
  DEFAULT_DEPLOYMENT,
  CONTAINER_HOSTNAMES,
  deploymentSchema,
  serviceOverrideSchema,
  parseDeployment,
  overlayDeployment,
  keepAwakeOf,
  keepAwakeSettingOf,
  shapeOf,
  enabled,
  servicePlan,
  usesCompose,
  resolveUrl,
  type Deployment,
  type DeploymentShape,
  type ServiceName,
  type ServiceOverride,
  type UrlContext,
  type Vantage,
} from "./deployment.js";
export {
  KEEP_AWAKE_VALUES,
  KEEP_AWAKE_DEFAULT,
  KEEP_AWAKE_RECOMMENDED,
  KEEP_AWAKE_CHOICES,
  KEEP_AWAKE_ENV,
  KEEP_AWAKE_KIND,
  KEEP_AWAKE_STATE_FILENAME,
  KEEP_AWAKE_CUTOFF_FACTOR,
  KEEP_AWAKE_REASON_MAX,
  LID_CLOSED_NOT_AVAILABLE,
  LID_CLOSED_DIALOG_TITLE,
  LID_CLOSED_COMMAND,
  LID_CLOSED_UNDO,
  LID_CLOSED_WARNING,
  PMSET_READS,
  isPmsetRead,
  parseSleepDisabled,
  keepAwakeObjectSchema,
  keepAwakeConfigSchema,
  keepAwakeSetting,
  keepAwakeValue,
  wantsLidClosedAwake,
  sameKeepAwake,
  keepAwakeReason,
  POWER_SOURCES,
  keepAwakeChoice,
  parseKeepAwake,
  parsePowerSource,
  powerSourceLabel,
  onWallPower,
  shouldHold,
  describeKeepAwake,
  keepAwakeStateSchema,
  keepAwakeCutoffSchema,
  parseKeepAwakeState,
  cutoffIsAFinding,
  humanGap,
  type KeepAwake,
  type KeepAwakeChoice,
  type KeepAwakeConfig,
  type KeepAwakeSetting,
  type KeepAwakeCutoff,
  type KeepAwakeState,
  type PowerSource,
} from "./power.js";
export {
  SUPERVISOR_LABEL,
  SUPERVISOR_SERVICE,
  SUPERVISOR_CONFIG_FILENAME,
  SUPERVISOR_SOCKET_FILENAME,
  RESTART_BACKOFF_MS,
  RESTART_BACKOFF_MAX_MS,
  RESTART_HEALTHY_MS,
  CRASH_LOOP_RESTARTS,
  CRASH_LOOP_WINDOW_MS,
  STOP_GRACE_MS,
  READY_TIMEOUT_MS,
  CONTROL_OPS,
  CONTROL_UNAUTHORIZED,
  childSpecSchema,
  readyProbeSchema,
  supervisorConfigSchema,
  controlRequestSchema,
  parseSupervisorConfig,
  type ChildSpec,
  type ChildSpecInput,
  type ChildState,
  type ChildStatus,
  type ControlOp,
  type ControlRequest,
  type ControlResponse,
  type ReadyProbe,
  type SupervisorConfig,
  type SupervisorConfigInput,
} from "./supervisor.js";
export {
  EGRESS_COMPONENT,
  EGRESS_DEFAULT_PORT,
  EGRESS_NO_PROXY,
  EGRESS_PROXY_DEFAULT_PORT,
  EGRESS_PROXY_ENV_VARS,
  EGRESS_PROXY_HOST,
  EGRESS_REALM,
  EGRESS_RUN_KIND,
  egressAllows,
  egressEntryFor,
  egressEntrySchema,
  egressProxyEnv,
  egressProxyUrl,
  egressSchema,
  describeDenial,
  isLoopbackHost,
  parseConnectTarget,
  parseEgressEntry,
  EGRESS_REFUSAL_CODES,
  SECRET_EGRESS_PURPOSES,
  EgressRefused,
  egressDestination,
  guardedFetch,
  planEgress,
  recordSecretUse,
  type Egress,
  type EgressCall,
  type EgressDenial,
  type EgressDestination,
  type EgressInput,
  type EgressPlan,
  type EgressRefusalCode,
  type EgressTarget,
  type SecretEgressPolicy,
  type SecretEgressPurpose,
  type SecretEgressRules,
} from "./egress.js";
export {
  CREDENTIAL_HELPER_RESET,
  DEFAULT_GIT_ACCOUNT,
  GIT_ASKPASS_PATH_VAR,
  GIT_ASKPASS_TOKEN_VAR,
  GIT_ASKPASS_USER_VAR,
  accountFromKeychainAttributes,
  gitCredentialSchema,
  type GitCredentialLookup,
} from "./git-credential.js";
export {
  AT_RE,
  DAY_SETS,
  EVERY,
  EVERY_SECONDS,
  LEGACY_CRON_RE,
  MAX_AT_TIMES,
  OCCURRENCE_REFUSALS,
  SCHEDULE_SHAPE_REFUSAL,
  WEEKDAYS,
  configuredTimeZone,
  describeSchedule,
  dueOccurrence,
  everySchema,
  intervalScheduleSchema,
  isInterval,
  isLegacyCron,
  longestGapSeconds,
  manifestScheduleSchema,
  nextOccurrence,
  resolveDays,
  scheduleSchema,
  scheduleToSeconds,
  timeOfDayScheduleSchema,
  validTimeZone,
  type DaySet,
  type Days,
  type Every,
  type IntervalSchedule,
  type ManifestSchedule,
  type NextOccurrence,
  type Occurrence,
  type OccurrenceContext,
  type OccurrenceRefusal,
  type ProfileFacts,
  type Schedule,
  type TimeOfDaySchedule,
  type Weekday,
} from "./schedule.js";
export {
  FIELD_ORIGINS,
  FIELD_ORIGIN_LABELS,
  MAX_TASK_CHARS,
  PROFILE_PATH,
  STANDUP_DEFAULT_AT,
  STANDUP_PROFILE_KEYS,
  STANDUP_ROUTINE,
  SCHEDULED_FILENAME,
  SCHEDULED_KEY_RE,
  SCHEDULED_NAME_RE,
  SCHEDULED_SECTIONS,
  checkScheduled,
  emptyScheduled,
  entryProblems,
  isAssignment,
  GRANTS_READ_ONLY_REFUSAL,
  ROUTINE_RUN_META_KEY,
  RUN_BEARER_META_KEY,
  grantArea,
  newRoutines,
  routineGrantsFor,
  routineRunMeta,
  routineRunReads,
  type RoutineRunMeta,
  resolveScheduled,
  resolveUnit,
  scheduledUnitOf,
  parseScheduled,
  planStandupMove,
  profileFacts,
  profileFrontmatter,
  profileTime,
  profileWeekdays,
  readStandupKeys,
  resolveScheduleDays,
  timeOfDayFields,
  withRoutineSchedule,
  withoutProfileKeys,
  routineAssignmentSchema,
  routineEntrySchema,
  routineOverrideSchema,
  scheduledSchema,
  syncEntrySchema,
  validateScheduled,
  type ConfigValue,
  type FieldOrigin,
  type Grants,
  type RoutineAssignment,
  type RoutineEntry,
  type ResolvedDays,
  type RoutineOverride,
  type Scheduled,
  type ResolveContext,
  type ResolvedScheduled,
  type ScheduledListing,
  type ScheduledProblem,
  type ScheduledResult,
  type ScheduledSection,
  type ScheduledUnit,
  type Sourced,
  type StandupKeys,
  type StandupMove,
  type StandupProfileKey,
  type SyncEntry,
} from "./scheduled.js";
export {
  COST_SOURCES,
  DEFAULT_CACHE_READ_MULTIPLIER,
  DEFAULT_CACHE_WRITE_MULTIPLIER,
  usageFromResponse,
  costOf,
  unpricedNote,
  type CallCost,
  type CallUsage,
  type CostSource,
} from "./cost.js";
export {
  BUDGET_EXCEEDED,
  BUDGET_WARN_FRACTION,
  BUDGET_WINDOWS,
  NO_SPEND,
  SPEND_QUERY,
  checkBudgets,
  budgetRefusalMessage,
  budgetWarningMessage,
  budgetWindowKey,
  budgetMiss,
  spentFrom,
  callsFrom,
  spendingLimits,
  PROJECTS_QUERY,
  type BudgetCheckInput,
  type BudgetHit,
  type BudgetMiss,
  type BudgetVerdict,
  type BudgetWindow,
  type SpendRow,
  type Spent,
  type DollarLimit,
  type WindowLimit,
  type ProviderLimit,
  type ProjectLimit,
  type SpendingLimits,
  type LimitProvider,
  type ProjectBudgetRow,
} from "./budget.js";
export {
  COMPUTE_FILENAME,
  COMPUTE_FILES_DEFAULT,
  RULES_FILES_DEFAULT,
  PROVIDER_KINDS,
  LOCALITIES,
  CACHING_MODES,
  DEFAULT_CACHING,
  BUDGET_ACTIONS,
  DEFAULT_BUDGET_ACTION,
  SECRET_NAME_RE,
  BILLINGS,
  PROVIDER_TAGS,
  credentialOf,
  credentialEnvNames,
  credentialFromEnv,
  providerCredential,
  providerSecretNames,
  providerEnabled,
  providerTag,
  PROVIDER_NAME_RE,
  providerSchema,
  assignmentSchema,
  assignmentsSchema,
  DEFAULT_MAX_OUTPUT_TOKENS,
  budgetSchema,
  budgetsSchema,
  computeSchema,
  engineStatus,
  engineConfigured,
  engineKindFor,
  crossKindRefusal,
  serveSchema,
  shadowSchema,
  resolveShadow,
  SERVE_RUNTIMES,
  servedProviders,
  collectorProviderIssue,
  firstOnMachineBaseUrl,
  modelRefIssue,
  parseModelRef,
  parseCompute,
  validateCompute,
  emptyCompute,
  assignsNothing,
  resolveAssignment,
  resolveCrewAssignment,
  intentAssignmentSchema,
  resolveIntentTier,
  PRIVATE_TIER,
  PrivateTierUnavailable,
  privateTierIssue,
  resolvePrivateTier,
  turnTier,
  computeTiers,
  computePaths,
  loadCompute,
  startComputeWatch,
  ComputeStore,
  type Assignment,
  type Assignments,
  type Billing,
  type Budget,
  type BudgetAction,
  type CachingMode,
  type ProviderCredential,
  type ProviderTag,
  type Budgets,
  type Compute,
  type CrossKindRefusal,
  type EngineKind,
  type EngineStatus,
  type ComputeReload,
  type ComputeResult,
  type ComputeWatch,
  type ComputeWatchOptions,
  type LoadedCompute,
  type Locality,
  type ModelRef,
  type Provider,
  type ProviderKind,
  type ReadFile,
  type IntentAssignment,
  type ResolvedAssignment,
  type CrewAssignment,
  type ResolvedIntentTier,
  type PrivateTierResolution,
  type ResolvedShadow,
  type Serve,
  type Shadow,
  type LlamaServe,
  type ServeRuntime,
  type WatchSeam,
} from "./compute.js";
export {
  MODEL_IDENTITIES_FILENAME,
  MODEL_CAPABILITIES,
  MODEL_IDENTITY_KEY_RE,
  modelIdentitiesSchema,
  parseModelIdentities,
  overlayModelIdentities,
  loadModelIdentities,
  identityIndex,
  groupCatalogue,
  type ModelCapability,
  type ModelIdentity,
  type ModelIdentities,
  type CatalogueEntry,
  type CataloguePlace,
  type CatalogueRow,
} from "./model-identities.js";
export {
  EFFORTS,
  DEFAULT_TIER,
  ROUTINE_TIER,
  tierSchema,
  tiersSchema,
  resolveTier,
  parseTiers,
  type Effort,
  type Tier,
  type TierMap,
  type ResolvedTier,
} from "./tiers.js";
export {
  INSTANCES_FILENAME,
  CAPABILITIES,
  AGENT_NAME_RE,
  INSTANCE_ID_RE,
  QUALIFIED_AGENT_RE,
  normalizeCapabilities,
  qualifyAgentId,
  qualifyIfPossible,
  parseAgentId,
  instanceEntrySchema,
  instancesSchema,
  emptyInstances,
  validateInstances,
  parseInstances,
  findInstance,
  type Capability,
  type InstanceEntry,
  type Instances,
  type InstancesResult,
} from "./instances.js";
export { rollSession, type RollResult } from "./session-roll.js";
export {
  INSTANCE_SECRET_NAME_RE,
  SECRET_DELIVERY_PREFIX,
  secretDeliveryVar,
  SECRET_SERVICE_PREFIX,
  SECRET_GRANT_MODES,
  DEFAULT_SECRET_GRANT,
  SECRET_GRANTEE_RE,
  SECRET_REF_RE,
  SECRET_USE_META_KEY,
  SECRET_LAST_USED_QUERY,
  InstanceSecrets,
  describeSecrets,
  fillSecretRefs,
  instancePresence,
  isSecretName,
  memoryKeychain,
  normalizeSecretHost,
  parseSecretGrantee,
  parseSecretReference,
  parseSecretsFile,
  secretAccount,
  secretEnvName,
  secretGrant,
  secretNameIssue,
  secretRefsIn,
  secretService,
  secretValueIssue,
  secretsFileSchema,
  type FillResult,
  type KeychainBackend,
  type SecretGrantMode,
  type SecretGrantee,
  type SecretPolicy,
  type SecretPresence,
  type SecretReference,
  type SecretRefs,
  type SecretRow,
  type SecretSource,
  type SecretsFile,
} from "./secrets.js";
export {
  NO_SCHEDULE_IN_VARIABLES,
  STORE_AS_SECRET,
  VARIABLE_NAME_RE,
  VARIABLE_REF_RE,
  VARIABLE_VALUE_MAX,
  describeVariables,
  fillVariableRefs,
  looksLikeKey,
  looksLikeSchedule,
  parseVariablesFile,
  readerOf,
  secretHeldIn,
  variableNameIssue,
  variableRefsIn,
  variableValueIssue,
  type VariableFillResult,
  type VariableIssue,
  type VariableRefs,
  type VariableRefusal,
  type VariableRow,
  type VariablesFile,
} from "./variables.js";
export {
  REDACTED,
  isSecretKeyName,
  redactSecrets,
  scrubModelOutput,
  containsRedactedPlaceholder,
  SecretRedactor,
  redactedSecret,
} from "./redact.js";
export { parseBearer, tokenEquals, authorized, tokenHash, mintToken } from "./auth.js";
export { sanitizeForAgent } from "./sanitize.js";
export {
  QUESTION_MAX_OPTION,
  QUESTION_MAX_OPTIONS,
  QUESTION_MAX_OTHER,
  QUESTION_MAX_PROMPT,
  QUESTION_MAX_COUNT,
  QUESTION_MAX_TITLE,
  QUESTION_MIN_OPTIONS,
  SKIP_FEEDBACK,
  answersText,
  checkAnswers,
  checkQuestions,
  parseDecisionBlock,
  questionsOf,
  v1Options,
  type DecisionBlock,
  type Question,
  type QuestionAnswer,
} from "./decision-block.js";
export {
  REQUEST_BODIES,
  REQUEST_DECISIONS,
  REQUEST_DOORS,
  REQUEST_KIND_TYPE,
  REQUEST_KINDS,
  REQUEST_SUBJECT_BASES,
  REQUEST_TYPE_SUBJECT,
  REQUEST_TYPE_TABLE,
  REQUEST_TYPES,
  UNKNOWN_KIND_BODY,
  UNKNOWN_KIND_TYPE,
  describeRequest,
  isRequestKind,
  parseSubjectFingerprint,
  requestBodyOf,
  requestSubjectOf,
  requestTypeOf,
  requestWordOf,
  requestWordSql,
  subjectFingerprint,
  subjectUnchanged,
  type RequestAnswer,
  type RequestBody,
  type RequestBodyAnswers,
  type RequestDecision,
  type RequestDoor,
  type RequestKind,
  type RequestSend,
  type RequestShape,
  type RequestSubject,
  type RequestSubjectBasis,
  type RequestType,
  type RequestTypeSpec,
  type SubjectReading,
} from "./requests.js";
export {
  KNOWLEDGE_CONFLICT_REF_PREFIX,
  KNOWLEDGE_CONFLICT_SOURCE_KIND,
  RESOLVED_AT_SOURCE,
  REQUEST_TRUSTS,
  knowledgeConflictSource,
  lastMirror,
  parseRequestSource,
  raiseMirror,
  resolveAtSource,
  type MirrorExecutor,
  type MirrorHistory,
  type MirrorRaise,
  type MirrorRaised,
  type RequestSource,
  type RequestTrust,
} from "./mirrors.js";
export {
  GITHUB_API_ORIGIN,
  GITHUB_SOURCE_KIND,
  GITHUB_WRITE_SECRET,
  HEAD_SHA_RE,
  PR_REVIEW_DECISION,
  PR_REVIEW_EVENTS,
  PR_REVIEW_GITHUB_EVENT,
  PULL_REQUEST_KIND,
  githubPullRef,
  githubPullSource,
  isHeadSha,
  parseGithubPullRef,
  parseGithubRepo,
  type PrReviewEvent,
} from "./github-pulls.js";
export {
  startRun,
  finishRun,
  withRun,
  type RunExecutor,
  type RunStart,
  type RunFinish,
} from "./runs.js";
export {
  DEFAULT_MAX_STREAK,
  DEFAULT_ALERT_DEDUPE_HOURS,
  RUNNER_KIND,
  SKIPPED_STREAK,
  PREFLIGHT_FAILED,
  SCHEDULE_HELD,
  SCHEDULED_KINDS,
  normalizeError,
  errorSignature,
  signatureTag,
  failureStreaks,
  streakFor,
  shouldAlert,
  type ComponentStreak,
  type AlertGate,
} from "./failure.js";
export {
  DEFAULT_PREFLIGHT_TIMEOUT_MS,
  NO_REQUIREMENTS,
  requirementsOf,
  preflight,
  blockedConfigMessage,
  type PreflightMiss,
  type PreflightOptions,
  type PreflightResult,
} from "./preflight.js";
export {
  ensureProject,
  getProject,
  toProjectRow,
  PROJECT_SLUG_RE,
  PROJECT_MODES,
  PROJECT_COLS,
  DEFAULT_MAX_OPEN_BUNDLES,
  type ProjectExecutor,
  type ProjectMode,
  type ProjectRow,
} from "./projects.js";
export {
  chunkMarkdown,
  vectorLiteral,
  EmbedClient,
  EmbedUnavailableError,
  CHUNK_TARGET_CHARS,
  CHUNK_OVERLAP_CHARS,
  EMBED_DEFAULT_URL,
  EMBED_DEFAULT_MODEL,
  EMBED_DEFAULT_DIM,
  EMBED_DEFAULT_BATCH,
  LOCAL_MODEL_URL_VAR,
  OLLAMA_URL_VAR,
  apiRootOf,
  resolveLocalModelUrl,
  type Chunk,
  type ChunkOptions,
  type EmbedClientOptions,
  type FetchLike,
  type LocalModelUrl,
} from "./embed.js";
export {
  summarizeTranscript,
  renderSessionNote,
  renderSessionBody,
  sessionTitle,
  idempotencyKey,
  formatDuration,
  repoNameFromPath,
  decodeProjectDir,
  textOf,
  clip,
  MAX_FILES,
  FIRST_PROMPT_CHARS,
  LAST_MESSAGE_CHARS,
  type SessionSummary,
} from "./session-summary.js";
export {
  ANCHOR_ALPHABET,
  ANCHOR_LENGTH,
  ANCHOR_PREFIX,
  EXT_REF_SCHEMES,
  PRIORITY_ALIASES,
  RECUR_UNITS,
  SIZE_ALIASES,
  SIZE_RANK,
  TASK_COMPAT_READERS,
  TASK_PRIORITIES,
  TASK_SIZES,
  UNSET_PRIORITY,
  calendarDate,
  formatTaskLine,
  isTaskAnchor,
  locateTaskLine,
  nextRecurrence,
  normalizeTaskText,
  parseTaskLine,
  replaceLine,
  resolveTaskDate,
  setTaskChecked,
  setTaskScheduled,
  SOMEDAY_TOKEN,
  TASK_KEY_RE,
  taskHashKey,
  taskLinesOf,
  taskToday,
  type LocatedTaskLine,
  type ParsedTaskLine,
  type TaskCheckEdit,
  type TaskCheckRefusal,
  type TaskDeferral,
  type TaskScheduleEdit,
  type TaskScheduleRefusal,
  type RecurUnit,
  type TaskCompatReader,
  type TaskDateOptions,
  type TaskPriority,
  type TaskRecurrence,
  type TaskSize,
} from "./task-line.js";
export {
  TASK_FILTER_FIELDS,
  TASK_FILTER_FLAGS,
  TASK_FILTER_NOT,
  TASK_FILTER_OPS,
  TASK_FILTER_PARAM_SPEC,
  TASK_ORDER_FIELDS,
  TASK_QUERY_NAME,
  TASK_STATUSES,
  compileTaskFilter,
  taskFilterParams,
  type ParsedTaskFilter,
  type TaskFilterClause,
  type TaskFilterField,
  type TaskFilterFlag,
  type TaskFilterInput,
  type TaskFilterNotParam,
  type TaskFilterOp,
  type TaskFilterParams,
  type TaskFilterResult,
  type TaskOrderField,
  type TaskOrderTerm,
  type TaskStatus,
} from "./task-filter.js";
export { addTaskDays } from "./task-line.js";
export {
  NOTE_SECTIONS,
  NOTE_SECTION_NAMES,
  SECTION_MISSING_REASONS,
  isNoteSectionName,
  scanNoteSection,
  sectionMissingMessage,
  writeNoteSection,
  type NoteSectionName,
  type NoteSectionScan,
  type NoteSectionSpec,
  type NoteSectionWrite,
  type SectionMissingReason,
} from "./note-section.js";
export {
  MAX_PROSE_LINE_CHARS,
  PROSE_PENDING,
  fillProseSlots,
  pendingProseSlots,
  proseLineProblem,
  proseMarker,
  writtenMarker,
  type ProseFill,
  type ProseSlot,
} from "./prose-slots.js";
export {
  DEFAULT_RECURRING_MAX_PER_DAY,
  DEFAULT_TEMPLATE_MAX_BYTES,
  FOLD_SOURCE,
  PROSE_REFUSAL,
  PROSE_SOURCES,
  RECURRING_QUERY,
  REQUESTS_QUERY,
  SECTION_EMPTY_MODES,
  TASK_RENDER_FORMS,
  TEMPLATE_BLOCK_VERB,
  TEMPLATE_ENGINE_VERSION,
  TEMPLATE_MISSING,
  TEMPLATE_UNREADABLE,
  TEMPLATE_VERBS,
  TEMPLATES_DIR,
  USER_SOURCE,
  WORK_FLAGS,
  WORK_QUERY,
  carriedTimes,
  formatTemplateDate,
  parseWorkWhere,
  provenanceFooter,
  renderTemplate,
  sectionOf,
  templateSkip,
  validateTemplate,
  vaultLink,
  type CalendarEvent,
  type CalendarProvider,
  type FindingSeverity,
  type ProseRequest,
  type SectionEmptyMode,
  type TaskRenderForm,
  type TemplateContext,
  type TemplateDirective,
  type TemplateFinding,
  type TemplateQueries,
  type TemplateReader,
  type TemplateRender,
  type TemplateSkip,
  type TemplateValidation,
  type TemplateVerb,
  type TemplateWarning,
  type ValidateOptions,
  type WorkFlag,
} from "./template.js";
