// @foldedspacelabs/metistry-connections — plan §2.6, T4-8a.
//
// Connection files read against the connection-type registry (`load.ts`,
// `catalog.ts`), the listing every surface renders (`describe.ts`), the
// pooled MCP client (`pool.ts`, `plan.ts`) and its check (`check.ts`); what a
// sync opens to read a builtin provider's connection (`sync.ts`), the
// `linear` provider itself (`linear.ts`, T4-24) and Send to Linear
// (`linear-issue.ts`, T4-25), and the `ics` provider — an iCalendar feed,
// parsed and expanded (`ics.ts`, T4-12) — and the `caldav` provider: read,
// write own and reply over RFC 6638 (`caldav.ts`, `dav-xml.ts`, T4-13) — and
// the `imap` provider: headers read and drafts appended over IMAP, with no
// path that sends (`imap.ts`, `imap-wire.ts`, T4-15).
// docs/ops/connections.md is the same contract in words.

export { CONNECTION_REFUSAL_CODES, ConnectionRefused, type ConnectionRefusalCode } from "./errors.js";
export {
  CONNECTION_FILE_RE,
  CONNECTION_STATUSES,
  connectionFileRules,
  judgeConnection,
  parseConnectionText,
  readConnections,
  typedValues,
  type ConnectionEntry,
  type ConnectionStatus,
} from "./load.js";
export {
  connectionFileFor,
  connectionsDirFor,
  loadInstanceCatalog,
  type CatalogRoots,
  type ConnectionCatalog,
  type InstanceCatalog,
  type Parsed,
} from "./catalog.js";
export { planDial, planFingerprint, planHttp, variableFiller, type CommandDial, type DialPlan, type HttpDial } from "./plan.js";
export { basicSource, pinnedDoor, type PinnedDoorOptions } from "./door.js";
export {
  DEFAULT_OAUTH_FLOW_TIMEOUT_MS,
  OAUTH_CALLBACK_PATH,
  OAUTH_ERROR_CODES,
  OAUTH_LOOPBACK_HOST,
  OAuthError,
  OAuthTokens,
  authorizationUrl,
  authorizeConnection,
  exchangeCode,
  newState,
  oauthClientOf,
  oauthSecretNames,
  oauthSource,
  openLoopback,
  pkceChallenge,
  pkcePair,
  refreshAccess,
  sameState,
  type AuthorizeOptions,
  type AuthorizeResult,
  type Loopback,
  type OAuthClientId,
  type OAuthClientPlan,
  type OAuthErrorCode,
  type TokenDoor,
  type TokenGrant,
  type TokenStore,
} from "./oauth.js";
export {
  GENERATED_BODY_MAX_BYTES,
  GENERATED_FEED_MAX_BYTES,
  GENERATED_FILE_MAX_BYTES,
  GENERATED_TYPES,
  GENERATED_WALK_MAX_FILES,
  apiUrl,
  callGenerated,
  generatedToolsFor,
  globMatcher,
  htmlText,
  isGeneratedType,
  parseFeed,
  planGenerated,
  probeGenerated,
  type FeedItem,
  type GeneratedContext,
  type GeneratedPlan,
  type GeneratedResult,
  type GeneratedToolDef,
  type GeneratedType,
} from "./generated.js";
export {
  ConnectionPool,
  DEFAULT_CONNECTION_CALL_TIMEOUT_MS,
  DEFAULT_CONNECTION_CONNECT_TIMEOUT_MS,
  DEFAULT_CONNECTION_IDLE_MS,
  connectionGrantee,
  type CallOutcome,
  type CallRequest,
  type ConnectionPoolOptions,
  type ListedTool,
  type PoolEvent,
  type UpstreamTool,
} from "./pool.js";
export { checkConnection, type ConnectionCheckMeta, type ImapCheckMeta } from "./check.js";
export { poolProxy, type PoolProxy } from "./proxy.js";
export {
  describeConnection,
  describeConnectionDetail,
  describeConnections,
  type ConnectionDetail,
  type ConnectionRow,
  type ConnectionToolRow,
  type ConnectionUser,
  type DescribeOptions,
  type ReachSummary,
} from "./describe.js";
export {
  consoleSecretNames,
  envSecretSource,
  instanceSyncOpener,
  openSyncHttp,
  syncReaders,
  syncSecretNames,
  syncTarget,
  type OAuthCache,
  type OpenSyncOptions,
  type OpenedSync,
  type SyncHttp,
  type SyncOpener,
  type SyncTarget,
} from "./sync.js";
export {
  ASSIGNED_ISSUES_QUERY,
  COMPLETE_ISSUE_MUTATION,
  ISSUES_BY_ID_QUERY,
  ISSUE_TO_COMPLETE_QUERY,
  LINEAR_CLOSED_STATE_TYPES,
  LINEAR_COMPLETE_TOOL,
  LINEAR_ERROR_CODES,
  LINEAR_GRAPHQL_URL,
  LINEAR_KEY_RE,
  LINEAR_MODULE,
  LINEAR_ORIGIN,
  LINEAR_STATE_TYPES,
  LINEAR_SYNC,
  LinearError,
  assignedOpenIssues,
  completeIssue,
  issuesById,
  linearQuery,
  linearRef,
  readIssue,
  type CompletedIssue,
  type LinearErrorCode,
  type LinearIssue,
} from "./linear.js";
export {
  ISSUE_CREATE_MUTATION,
  ISSUE_TITLE_MAX,
  TRACKER_CREATE_CAPABILITY,
  VIEWER_TEAMS_QUERY,
  createLinearIssue,
  issueTitle,
  trackerIssueId,
  viewerTeams,
  type CreateIssueRequest,
  type CreateIssueResult,
  type LinearTeam,
} from "./linear-issue.js";
export {
  ICS_ERROR_CODES,
  ICS_MAX_BYTES,
  ICS_MODULE,
  ICS_SYNC,
  IcsError,
  Zones,
  expandRule,
  icsOccurrences,
  knownZone,
  parseDuration,
  parseIcs,
  parseRule,
  readIcsFeed,
  timeOf,
  unescapeText,
  zonedMidnight,
  zonedToday,
  type ExpandOptions,
  type IcsComponent,
  type IcsErrorCode,
  type IcsOccurrence,
  type IcsParticipant,
  type IcsProperty,
  type IcsSkipped,
  type IcsTime,
  type Rule,
} from "./ics.js";
export {
  CALDAV_ERROR_CODES,
  CALDAV_KNOWN_SERVICES,
  CALDAV_MODULE,
  CALDAV_SYNC,
  CaldavError,
  GOOGLE_CALDAV_REFUSAL,
  RSVP_RESPONSES,
  caldavCalendars,
  caldavConnectionIssues,
  calendarAddress,
  changeOwnEvent,
  createOwnEvent,
  deleteOwnEvent,
  discoverCaldav,
  findCaldavEvent,
  foldLine,
  markOwner,
  newEventUid,
  planOwnChange,
  planReply,
  previewChangeEvent,
  previewCreateEvent,
  previewDeleteEvent,
  previewReply,
  readCaldav,
  renderOwnEvent,
  respondToInvitation,
  type CaldavAccount,
  type CaldavCalendar,
  type CaldavErrorCode,
  type CaldavOccurrence,
  type CaldavRead,
  type CaldavResource,
  type LineChange,
  type OwnEventChange,
  type OwnEventDraft,
  type OwnPreview,
  type ReplyPlan,
  type ReplyPreview,
  type RsvpResponse,
  type WriteResult,
} from "./caldav.js";
export { CALDAV_NS, DAV_NS, DavXmlError, parseMultistatus, parseXml, type DavResponse, type XmlElement } from "./dav-xml.js";
export {
  IMAP_COMMANDS,
  IMAP_ERROR_CODES,
  IMAP_FETCH_ITEMS,
  IMAP_HEADER_FIELDS,
  IMAP_KNOWN_SERVICES,
  IMAP_MAX_DRAFT_BYTES,
  IMAP_MAX_MESSAGES,
  IMAP_MODULE,
  IMAP_PROVENANCE,
  IMAP_REFUSED_COMMANDS,
  ImapError,
  ImapSession,
  decodeEncodedWords,
  defaultImapDialer,
  headerFields,
  imapCommandLine,
  imapConnectionIssues,
  openImap,
  parseAddresses,
  parseInternalDate,
  planDraft,
  searchDate,
  type AppendResult,
  type DraftConfirm,
  type DraftInput,
  type DraftPlan,
  type DraftPreview,
  type ImapCommand,
  type ImapDialer,
  type ImapErrorCode,
  type ImapExamined,
  type ImapMailbox,
  type ImapMessage,
  type ImapRead,
  type ImapReach,
  type MailAddress,
  type OpenImapOptions,
} from "./imap.js";
export { ImapWireError, ResponseFramer, decodeMailboxName, quoted, tokenize, type ImapValue } from "./imap-wire.js";
export {
  GOOGLE_API_HOST,
  GOOGLE_AUTHORIZE_HOST,
  GOOGLE_CALENDAR_ERROR_CODES,
  GOOGLE_CALENDAR_MODULE,
  GOOGLE_CALENDAR_ORIGIN,
  GOOGLE_CALENDAR_SYNC,
  GOOGLE_CALENDAR_URL,
  GOOGLE_EVENT_FIELDS,
  GOOGLE_LIST_FIELDS,
  GOOGLE_RSVP_RESPONSES,
  GOOGLE_TOKEN_HOST,
  GOOGLE_TOKEN_HOSTS,
  GoogleCalendarError,
  changeBody,
  changeOwnGoogleEvent,
  checkOwnEvent,
  createOwnGoogleEvent,
  deleteOwnGoogleEvent,
  googleCalendarConnectionIssues,
  googleOccurrence,
  newEventBody,
  newGoogleEventId,
  planGoogleReply,
  previewChangeGoogleEvent,
  previewCreateGoogleEvent,
  previewDeleteGoogleEvent,
  previewGoogleReply,
  readGoogleCalendar,
  replyBody,
  respondToGoogleInvitation,
  type GoogleCalendarErrorCode,
  type GoogleEventBody,
  type GoogleEventChange,
  type GoogleEventDraft,
  type GoogleOccurrence,
  type GoogleOwnPreview,
  type GoogleRead,
  type GoogleReplyBody,
  type GoogleReplyPlan,
  type GoogleReplyPreview,
  type GoogleRsvpResponse,
  type GoogleSkipped,
  type GoogleWriteResult,
} from "./google-calendar.js";
