// The askpass shim `metistry up` generates for the confined reconciler.
//
// Why a generated file rather than one checked into the repo: `GIT_ASKPASS`
// must name a single executable with no arguments, and the only interpreters
// the reconciler's profile allows are node and git. A shebang is therefore
// the mechanism — and the node path is install-specific (a bundled runtime,
// a Homebrew node, the Mac app's), so the first line cannot be written in
// advance. `#!/usr/bin/env node` is not an option either: `/usr/bin/env` is
// not exec-able under the profile, which is a feature.
//
// It is generated beside the `Metistry` symlink `up` already creates, in
// `<instance>/.metistry/state/bin/`, and granted exec by LITERAL in
// ops/sandbox/reconciler.sb.
//
// That directory is inside the reconciler's own writable tree, which looks
// like a weakness and is not one: `NODE_BIN` is already exec-allowed and
// node runs whatever JavaScript it can read, so "arbitrary code inside the
// sandbox" was never what the profile prevented. What it prevents is
// reaching outside, and a fourteen-line shim changes nothing about that.
// Putting the file somewhere read-only would buy the appearance of a
// guarantee rather than a guarantee — and the product checkout, the only
// read-only candidate, is a release tree reached through a `current`
// symlink that `metistry update` flips.
//
// What the shim can do is exactly one thing: print one of two environment
// variables. It takes no path, opens no file, and has no way to be pointed
// at a different secret.

import { GIT_ASKPASS_TOKEN_VAR, GIT_ASKPASS_USER_VAR, instanceStatePath } from "@foldedspacelabs/metistry-core";

export const ASKPASS_FILENAME = "git-askpass";

/** `<instance>/.metistry/state/bin/git-askpass` — beside `bin/Metistry`, for the same reason: it is derived, per-install state. */
export function askpassPath(stateRoot: string): string {
  return instanceStatePath(stateRoot, "bin", ASKPASS_FILENAME);
}

/**
 * The shim's whole source.
 *
 * git calls it as `<askpass> "<prompt>"` and reads one line of stdout. The
 * prompts are `Username for 'https://host': ` and `Password for
 * 'https://user@host': `, so the only decision is which of the two
 * variables to print — and anything that is not a username prompt is
 * answered with the token, because a prompt we do not recognise must not
 * silently answer with the account name.
 *
 * No argument is treated as a path, nothing is read from disk, and the
 * values never appear in argv — git passes the prompt, not the answer.
 */
export function askpassScript(nodeBin: string): string {
  return [
    `#!${nodeBin}`,
    "// Generated by `metistry up` for the confined reconciler — see",
    "// packages/cli/src/askpass.ts and ops/sandbox/reconciler.sb. It prints one",
    "// of two environment variables and can do nothing else. Regenerated on",
    "// every `up`; editing it is pointless.",
    'const prompt = process.argv[2] ?? "";',
    `const answer = /username/i.test(prompt) ? process.env.${GIT_ASKPASS_USER_VAR} : process.env.${GIT_ASKPASS_TOKEN_VAR};`,
    'if (typeof answer !== "string" || answer === "") {',
    '  process.stderr.write("metistry git-askpass: no credential in this process\'s environment — the supervisor found none in the login Keychain for this remote (metistry connect-repo)\\n");',
    "  process.exit(1);",
    "}",
    'process.stdout.write(answer + "\\n");',
    "",
  ].join("\n");
}

/**
 * The mode the shim is written with: git execs it, so it has to be
 * executable, and nothing but `up` ever writes it. Applied by the same call
 * that writes the bytes (`StepRunner.write`) rather than by a `chmod`
 * beside it — a file whose executability is a separate step is a file that
 * is sometimes not executable.
 */
export const ASKPASS_MODE = 0o755;
