// `metistry migrate-layout` — carry an existing instance from the legacy
// layout (vault in `Knowledge/`, config at the root) to the flat one (the
// instance directory IS the vault, machinery under `.metistry/`; owner's
// ruling 2026-09-17, docs/ops/instance-layout.md).
//
// Same shape as `migrate-inbox`: the shared StepRunner so `--dry-run` is the
// SAME code path with execution turned off, `git mv` for what git tracks and
// a plain move for what it does not, one commit at the end, and it restarts
// nothing — it prints the `metistry up` line and stops.
//
// THE PLAN IS BUILT BEFORE ANYTHING MOVES. `planMigration` only reads the
// filesystem; every refusal it can raise (a name collision at the root, a
// file collision inside `Inbox/`) is raised with the tree untouched, so a
// refused run is a no-op rather than a half-migrated instance. `--dry-run`
// prints exactly that plan.
//
// ORDER. The steps run in the order below, which differs from the order the
// ruling lists them in for one reason: a legacy root `inbox/` has to be
// normalised to `Inbox/` BEFORE `Knowledge/Inbox/` merges into it. macOS is
// case-insensitive, so with a lowercase `inbox/` at the root the merge target
// `Inbox/` "exists" and the merge would land the captures in a mis-cased
// directory that the reconciler's own casing rule (apps/reconciler/src/paths.ts
// PINNED_ROOTS) then refuses to write to.
//
//   1. preflight     a git repo, a legacy layout, a clean tree, nothing running
//   2. .metistry/    the config half moves under one dot-folder
//   3. state/        the derived half (gitignored, so a plain move)
//   4. Inbox/        the pre-#156 root `inbox/`, normalised and merged
//   5. vault         every entry of `Knowledge/` to the root; `Knowledge/` removed
//   6. .gitignore    rewritten to INSTANCE_GITIGNORE_LINES, user lines kept
//   7. database      one transaction; `Knowledge/` drops out of every stored path
//   8. .env          METISTRY_* values that spelled the old paths
//   9. commit        one commit, by the same author `init` and `migrate-inbox` use
//
// WHAT IT DOES NOT DO. launchd plists under `state/` are regenerated by
// `metistry up` from `ops/launchd/*.plist`, so this verb says so rather than
// editing generated files it does not own. It restarts nothing.

import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, rename, rm, rmdir } from "node:fs/promises";
import { join } from "node:path";
import { isScalar, isSeq, parseDocument } from "yaml";
import {
  INSTANCE_GITIGNORE_LINES,
  INSTANCE_LAYOUT,
  LEGACY_VAULT_DIR,
  SUPERVISOR_LABEL,
  isVaultPath,
  VAULT_ROOT_AREA,
  detectLayout,
  metistryPath,
  type InstanceLayoutShape,
} from "@foldedspacelabs/metistry-core";
import { COMMIT_AUTHOR } from "./init.js";
import type { Exec } from "./exec.js";
import { normalizeDir } from "./instance.js";
import { openMigrationSession, type MigrationSession } from "./migrate.js";
import { RECONCILER_LABEL } from "./protected-write.js";
import { StepFailed, StepRunner } from "./steps.js";

/** The commit this verb writes. One logical change, named after the verb that made it. */
export const MIGRATE_LAYOUT_MESSAGE = "Migrate to the flat instance layout (metistry migrate-layout)";

/**
 * Everything that moves from the instance root into `.metistry/`, by its
 * legacy bare name. The order is the order the plan prints in: files first,
 * then the config directories, then the derived `state/`.
 *
 * Longer than the ruling's own list on purpose. `instances.yaml` (the peer
 * registry), `sources.yaml` and `assistant-prompt.md` (the D4 overlay) are
 * written at the instance root by instances/compute verbs that predate the
 * flat layout, and leaving one behind would not merely orphan it: a lowercase
 * `instances.yaml` at the root of a FLAT instance is vault content by
 * `isVaultPath`, so the reconciler would index the peer registry as a note.
 */
export const METISTRY_MOVES = Object.freeze([
  "identity.yaml",
  "rules.yaml",
  "compute.yaml",
  "deployment.yaml",
  "instances.yaml",
  "sources.yaml",
  "assistant-prompt.md",
  "metistry.lock",
  "agents",
  "routines",
  "queries",
  "extensions",
  "instance-migrations",
  "targets",
  // The bake-off's fixtures and transcripts (docs/poc/poc18-bakeoff). They are
  // instance-repo content, not knowledge: left at the root of a FLAT instance
  // a lowercase `eval/` is vault content by `isVaultPath`, so the reconciler
  // would index harvested transcripts as notes. Optional like every other
  // entry here — only moved if it is there.
  "eval",
] as const);

/** The derived half. Gitignored in both layouts, so it never goes through `git mv`. */
export const STATE_MOVE = "state";

/** The intermediate name a same-name-different-case rename passes through (macOS would otherwise move a directory inside itself). */
export const TEMP_SUFFIX = "-migrating";

/** One filesystem move in the plan, instance-relative and POSIX. */
export interface LayoutMove {
  from: string;
  to: string;
  /** `rename` = a two-step rename through a temp name (same name, different case); `merge` = this entry's CONTENTS move, because the destination already exists. */
  via?: "rename" | "merge";
}

export interface LayoutPlan {
  layout: InstanceLayoutShape;
  /** the real spelling of the legacy vault directory on this filesystem (`Knowledge`, or `knowledge` on an instance that spelled it that way) */
  vaultDir?: string | undefined;
  moves: LayoutMove[];
  /** the legacy vault directory, removed once empty */
  removeVaultDir?: string | undefined;
  /** things the operator should see but that do not stop the migration */
  warnings: string[];
  /** root entries that will be walked as vault content and break the TitleCase casing rule (CLAUDE.md) */
  lowercaseVaultRoots: string[];
}

/** A name collision this verb refuses on, with both sides named. */
export class LayoutCollision extends StepFailed {
  constructor(public readonly collisions: string[]) {
    super(
      `${collisions.length} name collision(s) between ${LEGACY_VAULT_DIR}/ and the instance root — nothing was moved:\n` +
        collisions.map((c) => `  ${c}`).join("\n") +
        `\nRename or remove one side of each, then re-run. (A ${LEGACY_VAULT_DIR}/Inbox and a root inbox/ are merged instead; these are not that.)`,
    );
  }
}

/** Finder metadata, regenerated on sight. Never a collision worth refusing a migration over. */
const NOISE = new Set([".DS_Store"]);

/**
 * Lowercase vault-root names the PRODUCT itself ships (`seed/vault/`), and so
 * not a casing surprise anybody needs telling about. `now.md` is the only one:
 * it is where `brain-commit` writes, and the plan spells it lowercase on
 * purpose. Warning about it would fire on every instance that has ever
 * existed, and a warning that always fires is one nobody reads.
 */
const SEED_VAULT_LOWERCASE = new Set(["now.md"]);

async function entriesOf(dir: string): Promise<string[]> {
  return (await readdir(dir).catch(() => [] as string[])).sort();
}

/**
 * The whole migration, read off disk and decided before a byte moves.
 *
 * Reads only. Throws `LayoutCollision` when two entries would land on the
 * same root name — which is the one failure mode that must be discovered
 * with the tree still intact.
 */
export async function planMigration(dir: string): Promise<LayoutPlan> {
  const layout = detectLayout(dir);
  const warnings: string[] = [];
  const moves: LayoutMove[] = [];
  if (layout !== "legacy") return { layout, moves, warnings, lowercaseVaultRoots: [] };

  const root = await entriesOf(dir);
  const has = (name: string) => root.includes(name);
  const realRoot = (name: string) => root.find((e) => e.toLowerCase() === name.toLowerCase());

  // 2 + 3: the config half and the derived half, into `.metistry/`.
  for (const name of [...METISTRY_MOVES, STATE_MOVE]) {
    if (!has(name)) continue;
    const to = `${INSTANCE_LAYOUT.metistryDir}/${name}`;
    if (existsSync(join(dir, to))) {
      warnings.push(`both ${name} and ${to} exist — left alone; an interrupted run leaves this, and only you can say which copy is current`);
      continue;
    }
    moves.push({ from: name, to });
  }

  // 4: the pre-#156 root `inbox/`, normalised to the one spelling the
  // reconciler accepts. On a case-insensitive filesystem there is only ever
  // one of these; on Linux there can be two, and the mis-cased one merges.
  const inboxes = root.filter((e) => e.toLowerCase() === INSTANCE_LAYOUT.inboxDir.toLowerCase());
  const canonicalInbox = inboxes.includes(INSTANCE_LAYOUT.inboxDir);
  for (const spelled of inboxes) {
    if (spelled === INSTANCE_LAYOUT.inboxDir) continue;
    if (canonicalInbox) {
      const collisions = await mergeCollisions(dir, spelled, INSTANCE_LAYOUT.inboxDir);
      if (collisions.length > 0) throw new LayoutCollision(collisions);
      moves.push({ from: spelled, to: INSTANCE_LAYOUT.inboxDir, via: "merge" });
    } else {
      moves.push({ from: spelled, to: INSTANCE_LAYOUT.inboxDir, via: "rename" });
    }
  }

  // 5: the vault itself. Every entry of `Knowledge/` becomes a root entry —
  // `Knowledge/CLAUDE.md` included, which is how the assistant's operating
  // instructions reach the root `CLAUDE.md` the layout names.
  const vaultDir = realRoot(LEGACY_VAULT_DIR);
  let removeVaultDir: string | undefined;
  if (vaultDir) {
    removeVaultDir = vaultDir;
    const collisions: string[] = [];
    // What is still at the root when the vault entries land: everything, less
    // the config half (now under `.metistry/`) and less the vault directory
    // itself, plus the canonically-spelled `Inbox/` step 4 leaves behind.
    const rootAfter = new Set(root);
    for (const m of moves) if (!m.from.includes("/")) rootAfter.delete(m.from);
    rootAfter.delete(vaultDir);
    for (const spelled of inboxes) rootAfter.delete(spelled);
    if (inboxes.length > 0) rootAfter.add(INSTANCE_LAYOUT.inboxDir);
    for (const entry of await entriesOf(join(dir, vaultDir))) {
      const from = `${vaultDir}/${entry}`;
      if (NOISE.has(entry)) {
        warnings.push(`${from} is Finder metadata — removed rather than moved`);
        moves.push({ from, to: "" });
        continue;
      }
      const clash = [...rootAfter].find((e) => e.toLowerCase() === entry.toLowerCase());
      if (clash === undefined) {
        moves.push({ from, to: entry });
        rootAfter.add(entry);
        continue;
      }
      // The one mergeable name: captures. Everything else is a refusal.
      if (entry.toLowerCase() === INSTANCE_LAYOUT.inboxDir.toLowerCase()) {
        const fileClashes = await mergeCollisions(dir, from, clash);
        if (fileClashes.length > 0) collisions.push(...fileClashes);
        else moves.push({ from, to: clash, via: "merge" });
        continue;
      }
      collisions.push(`${from} → ${entry} (the instance root already has ${clash})`);
    }
    if (collisions.length > 0) throw new LayoutCollision(collisions);
  }

  // What the vault root will hold, and which of it breaks the casing rule.
  // CLAUDE.md: vault content is TitleCase because Obsidian renders it and a
  // Linux container does not forgive `areas/`. After this migration the vault
  // root IS the instance root, so a lowercase directory that was merely
  // sitting beside the vault becomes vault content the reconciler walks,
  // indexes and embeds. That is a surprise worth seeing BEFORE the commit,
  // not after the first `metistry up`.
  const projectedRoot = new Set(root);
  for (const m of moves) {
    if (!m.from.includes("/")) projectedRoot.delete(m.from);
    if (m.to !== "" && !m.to.includes("/")) projectedRoot.add(m.to);
  }
  if (vaultDir) projectedRoot.delete(vaultDir);
  const lowercaseVaultRoots = [...projectedRoot].filter((e) => isVaultPath(e) && !SEED_VAULT_LOWERCASE.has(e) && e[0] !== e[0]?.toUpperCase()).sort();

  return { layout, vaultDir, moves, removeVaultDir, warnings, lowercaseVaultRoots };
}

/** Files that exist on both sides of a directory merge, as `src → dst` lines. Empty = the merge is safe. */
async function mergeCollisions(dir: string, from: string, to: string): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await entriesOf(join(dir, from))) {
    if (NOISE.has(entry)) continue;
    if (existsSync(join(dir, to, entry))) out.push(`${from}/${entry} → ${to}/${entry} (already exists)`);
  }
  return out;
}

// ---- .gitignore -----------------------------------------------------------

/**
 * Lines the flat layout's own set supersedes, normalised (leading slash and
 * trailing slash dropped). Anything NOT in here is something the user added
 * and is carried through verbatim, comments and all.
 */
const SUPERSEDED = new Set(
  [
    "state",
    "inbox",
    ".obsidian/workspace*",
    `${LEGACY_VAULT_DIR}/Inbox/.large`,
    `${LEGACY_VAULT_DIR}/inbox/.large`,
    "Inbox/.large",
    ".metistry/state",
  ].map((l) => l.toLowerCase()),
);

const normalizeIgnoreLine = (l: string) => l.trim().replace(/^\//, "").replace(/\/$/, "").toLowerCase();

/**
 * `.gitignore` for the flat layout: the canonical block from core, then every
 * line this instance added that the block does not already cover.
 *
 * The canonical block goes FIRST and verbatim so a migrated instance's file is
 * byte-comparable with what `metistry init` stamps today; a hand-added rule
 * keeps its place relative to the other hand-added rules.
 */
export function rewriteGitignore(existing: string): string {
  const canonical = new Set(INSTANCE_GITIGNORE_LINES.map(normalizeIgnoreLine));
  const kept: string[] = [];
  for (const raw of existing.split("\n")) {
    const norm = normalizeIgnoreLine(raw);
    if (raw.trim() === "") continue; // blank lines are re-introduced below, once
    if (canonical.has(norm) || SUPERSEDED.has(norm)) continue;
    kept.push(raw.replace(/\s+$/, ""));
  }
  return `${[...INSTANCE_GITIGNORE_LINES, ...(kept.length > 0 ? ["", ...kept] : [])].join("\n")}\n`;
}

// ---- state/.env -----------------------------------------------------------

/** Legacy instance-root names whose flat spelling is the same name under `.metistry/`. */
const CONFIG_NAMES = [...METISTRY_MOVES, STATE_MOVE] as readonly string[];
/** The subset that is a FILE: a bare relative one of these in a `*_FILES` overlay is unambiguously the instance's copy (the product's live under `seed/`). */
const CONFIG_FILES = METISTRY_MOVES.filter((n) => n.includes("."));

/**
 * One `METISTRY_*` value, rewritten for the flat layout. Pure: `instanceDir`
 * is only ever compared against, never read.
 *
 * Three rules, and deliberately no fourth:
 *
 *   1. a `Knowledge/` prefix is dropped (`<instance>/Knowledge/Inbox` →
 *      `<instance>/Inbox`), and a bare `Knowledge/` — the old whole-vault
 *      grant sentinel in `METISTRY_ASSISTANT_AREAS` — becomes VAULT_ROOT_AREA;
 *   2. `<instanceDir>/<config>` becomes `<instanceDir>/.metistry/<config>`;
 *   3. a bare relative config FILE (`rules.yaml`, `compute.yaml`, …) becomes
 *      `.metistry/<file>`.
 *
 * A bare relative config DIRECTORY (`targets`, `routines`, `queries`) is left
 * alone and warned about instead: the product checkout has directories by
 * those names too, so `METISTRY_TARGETS_DIRS=targets` means the PRODUCT's
 * `targets/`, and rewriting it would point the console at an instance
 * directory the user never asked for. Guessing wrong there is worse than
 * saying so — the flat default is `targets:.metistry/targets`, and the
 * warning prints it.
 */
export function rewriteEnvValue(key: string, value: string, instanceDir: string): { value: string; warnings: string[] } {
  // The instance dir is where everything else is relative TO; it does not move.
  // A URL is not a path list — `http://127.0.0.1:7812` has colons that mean
  // something else entirely, so it is returned untouched rather than split.
  if (key === "METISTRY_INSTANCE_DIR" || /:\/\//.test(value)) return { value, warnings: [] };
  const warnings: string[] = [];
  // Overlays are colon-separated (D4, "last existing wins"); grant and slug
  // lists are comma-separated (`METISTRY_ASSISTANT_AREAS`).
  const sep = /_(AREAS|PROJECTS|REPOS)$/.test(key) ? "," : ":";
  const dir = normalizeDir(instanceDir);
  const out = value.split(sep).map((raw) => {
    const seg = raw.trim();
    if (seg === "") return raw;
    // 1 — the vault prefix, absolute or relative
    if (seg === LEGACY_VAULT_DIR || seg === `${LEGACY_VAULT_DIR}/`) return VAULT_ROOT_AREA;
    if (seg.startsWith(`${LEGACY_VAULT_DIR}/`)) return seg.slice(LEGACY_VAULT_DIR.length + 1);
    if (dir && seg.startsWith(`${dir}/${LEGACY_VAULT_DIR}/`)) return `${dir}/${seg.slice(dir.length + LEGACY_VAULT_DIR.length + 2)}`;
    // 2 — an absolute path into this instance's config half
    if (dir && seg.startsWith(`${dir}/`)) {
      const rel = seg.slice(dir.length + 1);
      const head = rel.split("/")[0] ?? "";
      if (CONFIG_NAMES.includes(head)) return `${dir}/${INSTANCE_LAYOUT.metistryDir}/${rel}`;
      return seg;
    }
    // 3 — a bare relative config file
    const head = seg.split("/")[0] ?? "";
    if ((CONFIG_FILES as readonly string[]).includes(seg)) return `${INSTANCE_LAYOUT.metistryDir}/${seg}`;
    if (CONFIG_NAMES.includes(head) && !seg.startsWith(`${INSTANCE_LAYOUT.metistryDir}/`)) {
      warnings.push(
        `${key} names a bare \`${seg}\` — the product checkout has a directory by that name too, so this verb will not guess. The flat spelling of an instance's own copy is \`${INSTANCE_LAYOUT.metistryDir}/${seg}\`.`,
      );
    }
    return seg;
  });
  return { value: out.join(sep), warnings };
}

/** Every `KEY=value` line the flat layout changes, with the lines it leaves alone untouched (comments, spacing, quoting). */
export function rewriteEnvFile(text: string, instanceDir: string): { text: string; changed: { key: string; from: string; to: string }[]; warnings: string[] } {
  const changed: { key: string; from: string; to: string }[] = [];
  const warnings: string[] = [];
  const lines = text.split("\n").map((raw) => {
    const m = /^(\s*(?:export\s+)?)(METISTRY_[A-Z0-9_]*)=(.*)$/.exec(raw);
    if (!m) return raw;
    const [, lead = "", key = "", rest = ""] = m;
    const quote = rest.length >= 2 && ((rest.startsWith('"') && rest.endsWith('"')) || (rest.startsWith("'") && rest.endsWith("'"))) ? rest[0]! : "";
    const bare = quote ? rest.slice(1, -1) : rest;
    const r = rewriteEnvValue(key, bare, instanceDir);
    warnings.push(...r.warnings);
    if (r.value === bare) return raw;
    changed.push({ key, from: bare, to: r.value });
    return `${lead}${key}=${quote}${r.value}${quote}`;
  });
  return { text: lines.join("\n"), changed, warnings };
}

// ---- manifests ------------------------------------------------------------
//
// A crew's `scope:` and a target's `data_policy.allow:` are vault path
// prefixes, and they live in FILES in the instance repo — not in the database.
// Rewriting `agents.grants` without rewriting the manifest behind it is a
// migration that silently fails: the console re-syncs the registry from
// `.metistry/agents/**` on an interval (METISTRY_CREWS_SYNC_S), and the next
// sync writes the legacy scope straight back over the migrated grant.
//
// A YAML-DOCUMENT edit, and then a SPLICE rather than a re-print. Every one of
// these files is hand-written and commented — `seed/agents/example/researcher.md`
// is eleven comment lines to nine keys, with the comments column-aligned — and
// a manifest that came back reformatted would be a worse outcome than the
// stale prefix.
//
// `parseDocument` is what locates the entries (the same parser the console
// validates them with, so this can never disagree with it about which
// scalars are areas), but what gets written is the ORIGINAL text with only
// those scalars' own byte ranges replaced. `String(doc)` was the first cut
// and it was rejected on sight: printing the seed crew back collapsed the
// aligned `# haiku | sonnet | opus` comments onto one space and turned
// `[knowledge, requests]` into `[ knowledge, requests ]` — eight reformatted
// lines to carry one real change. Splicing gives exactly one changed
// substring per entry, and the operating prompt below the frontmatter is
// never even read.

/** `agents/<area>/<name>.md`, and the frontmatter/prompt split crews.ts parses. */
const FRONTMATTER = /^(---\r?\n)([\s\S]*?)(\r?\n---\r?\n?)/;

/** Where a vault path prefix can appear in a manifest: a crew's scope, a target's allow-list. */
export const MANIFEST_AREA_KEYS = Object.freeze([["scope"], ["data_policy", "allow"]] as const);

/**
 * One area entry, for the flat layout.
 *
 * `Knowledge/<Area>` simply loses the prefix. A BARE `Knowledge` (or
 * `Knowledge/`) is left exactly as it is, with a warning, because it has no
 * valid flat spelling here: it meant "the whole vault", and the old schema
 * admitted it (`^Knowledge(\/[A-Za-z0-9_.-]+)*$` — note the `*`), but core's
 * `knowledgePrefix` refuses a leading slash and a crew `scope` refuses
 * VAULT_ROOT_AREA outright. Writing `/` there would produce a manifest that
 * fails validation, which revokes the crew's registry row — strictly worse
 * than a prefix the owner can see and resolve. The bare vault survives only
 * as a DB grant, for an internal principal (agents.grants, above).
 */
export function rewriteManifestArea(value: string): { value: string; warning?: string } {
  if (value === LEGACY_VAULT_DIR || value === `${LEGACY_VAULT_DIR}/`) {
    return {
      value,
      warning: `"${value}" means the whole vault, and neither a crew scope nor a target allow-list has a flat spelling for that — left as it is. Name the areas it should cover (e.g. Areas, Projects) before the next crew sync, or the manifest is refused whole.`,
    };
  }
  if (value.startsWith(`${LEGACY_VAULT_DIR}/`)) return { value: value.slice(LEGACY_VAULT_DIR.length + 1) };
  return { value };
}

/** One scalar's own byte range in the source, and the text to put there. */
interface Splice {
  start: number;
  end: number;
  text: string;
}

/** The area scalars under `keyPath`, as splices against the source. Nothing is mutated. */
function spliceSeq(doc: ReturnType<typeof parseDocument>, keyPath: readonly string[], src: string): { splices: Splice[]; changed: string[]; warnings: string[] } {
  const splices: Splice[] = [];
  const changed: string[] = [];
  const warnings: string[] = [];
  const node = doc.getIn([...keyPath], true);
  if (!isSeq(node)) return { splices, changed, warnings };
  for (const item of node.items) {
    if (!isScalar(item) || typeof item.value !== "string" || !item.range) continue;
    const r = rewriteManifestArea(item.value);
    if (r.warning) warnings.push(`${keyPath.join(".")}: ${r.warning}`);
    if (r.value === item.value) continue;
    // The raw token, quotes and all. The rewrite only ever DROPS a leading
    // `Knowledge/` from the value, so replacing that substring inside the raw
    // token is correct for a plain, single- and double-quoted scalar alike —
    // and it cannot change the token's kind, which is what makes re-quoting a
    // question that never has to be asked.
    const [start, end] = [item.range[0], item.range[1]];
    const raw = src.slice(start, end);
    const text = raw.replace(`${LEGACY_VAULT_DIR}/`, "");
    if (text === raw) continue;
    splices.push({ start, end, text });
    changed.push(`${item.value} → ${r.value}`);
  }
  return { splices, changed, warnings };
}

/**
 * One manifest's areas, rewritten. Handles both shapes: a crew is YAML
 * frontmatter inside a `.md`, a target is a whole `manifest.yaml`. Returns
 * the text unchanged (and `changed: []`) when there was nothing to do, so the
 * caller can leave the file's mtime alone.
 */
export function rewriteManifestAreas(text: string): { text: string; changed: string[]; warnings: string[] } {
  const fm = FRONTMATTER.exec(text);
  // Offsets are into the YAML half, so the frontmatter's opening `---\n` is
  // the amount every splice has to be shifted by to land in the whole file.
  const offset = fm ? fm[1]!.length : 0;
  const yamlText = fm ? fm[2]! : text;
  let doc: ReturnType<typeof parseDocument>;
  try {
    doc = parseDocument(yamlText);
  } catch {
    return { text, changed: [], warnings: ["not YAML this verb can edit — left untouched"] };
  }
  if (doc.errors.length > 0) return { text, changed: [], warnings: [`YAML errors (${doc.errors[0]?.message ?? "?"}) — left untouched`] };
  const splices: Splice[] = [];
  const changed: string[] = [];
  const warnings: string[] = [];
  for (const keyPath of MANIFEST_AREA_KEYS) {
    const r = spliceSeq(doc, keyPath, yamlText);
    splices.push(...r.splices);
    changed.push(...r.changed);
    warnings.push(...r.warnings);
  }
  if (splices.length === 0) return { text, changed, warnings };
  // Back to front, so an earlier splice never moves a later one's offsets.
  let out = text;
  for (const sp of [...splices].sort((a, b) => b.start - a.start)) {
    out = out.slice(0, sp.start + offset) + sp.text + out.slice(sp.end + offset);
  }
  return { text: out, changed, warnings };
}

/** Every manifest under `dir` that could carry a vault prefix: `*.md` crews at any depth, and any `manifest.yaml`. */
async function manifestsUnder(dir: string, rel = ""): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await entriesOf(join(dir, rel))) {
    if (entry.startsWith(".")) continue;
    const child = rel ? `${rel}/${entry}` : entry;
    const nested = await readdir(join(dir, child)).catch(() => null);
    if (nested !== null) out.push(...(await manifestsUnder(dir, child)));
    else if (entry.endsWith(".md") || entry === "manifest.yaml") out.push(child);
  }
  return out;
}

// ---- the database ---------------------------------------------------------

/**
 * One rewrite: what it is called, how many rows still need it, and the
 * statement that does it. `count` is what `--dry-run` asks (a SELECT touches
 * nothing); `update` is what the real run runs, all of them in ONE
 * transaction so the instance's stored paths can never be half-migrated.
 *
 * WHAT IS HERE, AND WHAT IS DELIBERATELY NOT. Every column below holds a
 * VAULT-RELATIVE path, which is exactly what the ruling moved. Three other
 * path-shaped columns exist and are left alone:
 *
 *   * `artifact_versions.path_prefix` — `Artifacts/<project>/<slug>`, and
 *     `Artifacts/` was already at the instance root before the ruling
 *     (NON_VAULT_ROOTS); nothing about it moved.
 *   * `artifact_comments.path` — one file WITHIN a version, relative to that
 *     prefix. Not a vault path at all.
 *   * `runs.meta` — the audit trail. It records what a component did at the
 *     time it did it; rewriting it would falsify the record (invariant 1's
 *     whole point is that the record is not edited to suit the present).
 *
 * `work.area` is a free-text rollup label the collectors write (`fsl`), not a
 * vault prefix, and is left alone too. `projects.area` IS documented as a
 * vault area (db/migrations/0011_projects.sql) and is rewritten.
 */
export interface DbRewrite {
  name: string;
  count: string;
  update: string;
}

/** `Knowledge/x` → `x` for a plain vault-path column. */
const stripPrefix = (table: string, column: string): DbRewrite => ({
  name: `${table}.${column}`,
  count: `SELECT count(*)::int AS n FROM ${table} WHERE ${column} LIKE '${LEGACY_VAULT_DIR}/%'`,
  update: `UPDATE ${table} SET ${column} = substring(${column} from ${LEGACY_VAULT_DIR.length + 2}) WHERE ${column} LIKE '${LEGACY_VAULT_DIR}/%'`,
});

/**
 * The `agents.grants` rewrite. `areas` is a jsonb array of strings: the bare
 * vault grant was the vault directory's name with a slash (`Knowledge/`) and
 * is now VAULT_ROOT_AREA (`/`, core's instance-layout.ts — with the vault AT
 * the root there is no name to say); every other entry simply loses the
 * prefix. `jsonb_typeof` guards a row whose `areas` is not an array, which
 * `jsonb_array_elements_text` would error on rather than skip.
 */
const GRANTS_PREDICATE = `jsonb_typeof(grants->'areas') = 'array' AND EXISTS (
    SELECT 1 FROM jsonb_array_elements_text(grants->'areas') AS t(e)
     WHERE e = '${LEGACY_VAULT_DIR}' OR e = '${LEGACY_VAULT_DIR}/' OR e LIKE '${LEGACY_VAULT_DIR}/%')`;

const GRANTS: DbRewrite = {
  name: "agents.grants.areas",
  count: `SELECT count(*)::int AS n FROM agents WHERE ${GRANTS_PREDICATE}`,
  update: `UPDATE agents a
   SET grants = jsonb_set(a.grants, '{areas}', COALESCE(n.areas, '[]'::jsonb))
  FROM (SELECT id, jsonb_agg(DISTINCT v ORDER BY v) AS areas FROM (
          SELECT ag.id,
                 CASE WHEN e IN ('${LEGACY_VAULT_DIR}', '${LEGACY_VAULT_DIR}/') THEN '${VAULT_ROOT_AREA}'
                      WHEN e LIKE '${LEGACY_VAULT_DIR}/%' THEN substring(e from ${LEGACY_VAULT_DIR.length + 2})
                      ELSE e END AS v
            FROM agents ag, jsonb_array_elements_text(ag.grants->'areas') AS t(e)
           WHERE jsonb_typeof(ag.grants->'areas') = 'array') s
        GROUP BY id) n
 WHERE a.id = n.id AND ${GRANTS_PREDICATE.replace(/grants->/g, "a.grants->")}`,
};

/**
 * The capture rows, in three passes because a row can be in three shapes:
 * a bare filename (pre-2026-09-16, before captures were vault content at
 * all), `Knowledge/Inbox/<file>` in either casing, and any other
 * `Knowledge/…` path. Order matters — the bare pass must run before the
 * prefix passes, or a bare name would be untouched by all three.
 */
const INBOX_REWRITES: DbRewrite[] = [
  {
    name: "inbox.path (bare filename → Inbox/)",
    count: `SELECT count(*)::int AS n FROM inbox WHERE path NOT LIKE '%/%'`,
    update: `UPDATE inbox SET path = '${INSTANCE_LAYOUT.inboxDir}/' || path WHERE path NOT LIKE '%/%'`,
  },
  {
    name: `inbox.path (${LEGACY_VAULT_DIR}/Inbox/ → Inbox/)`,
    count: `SELECT count(*)::int AS n FROM inbox WHERE path ~ '^${LEGACY_VAULT_DIR}/[Ii]nbox/'`,
    update: `UPDATE inbox SET path = regexp_replace(path, '^${LEGACY_VAULT_DIR}/[Ii]nbox/', '${INSTANCE_LAYOUT.inboxDir}/') WHERE path ~ '^${LEGACY_VAULT_DIR}/[Ii]nbox/'`,
  },
  stripPrefix("inbox", "path"),
];

/** Every rewrite this verb runs, in order. Exported so the docs and the tests read the same list. */
export const DB_REWRITES: readonly DbRewrite[] = Object.freeze([
  stripPrefix("knowledge_files", "path"),
  stripPrefix("knowledge_links", "from_path"),
  stripPrefix("knowledge_links", "to_path"),
  stripPrefix("embeddings", "path"),
  ...INBOX_REWRITES,
  GRANTS,
  stripPrefix("projects", "area"),
]);

// ---- the verb -------------------------------------------------------------

export interface MigrateLayoutOptions {
  instanceDir: string;
  env?: NodeJS.ProcessEnv | undefined;
  exec?: Exec | undefined;
  out?: ((line: string) => void) | undefined;
  dryRun?: boolean | undefined;
  /** migrate on top of uncommitted work. Refused by default: a `git mv` storm over a dirty tree is not reviewable. */
  allowDirty?: boolean | undefined;
  /** test seam: a single-session db handle (null = no db configured, so rows are reported and skipped) */
  openSession?: ((env: NodeJS.ProcessEnv) => Promise<(MigrationSession & { end(): Promise<void> }) | null>) | undefined;
  platform?: NodeJS.Platform | undefined;
  uid?: number | undefined;
}

export interface MigrateLayoutResult {
  code: number;
  layout: InstanceLayoutShape;
  /** true when the instance was already flat — nothing ran */
  alreadyFlat: boolean;
  commands: string[];
  moves: LayoutMove[];
  /** `<rewrite name>` → rows rewritten (or, in a dry run, rows that still need it) */
  rows: Record<string, number>;
  /** false when no database was configured: the counts are unknown and the rewrite was skipped */
  database: boolean;
  gitignore: "updated" | "unchanged";
  /** manifests whose vault prefixes were rewritten, with what changed in each */
  manifests: { file: string; changed: string[] }[];
  env: { key: string; from: string; to: string }[];
  committed: boolean;
  warnings: string[];
}

export async function migrateLayout(opts: MigrateLayoutOptions): Promise<MigrateLayoutResult> {
  const dir = normalizeDir(opts.instanceDir);
  const env = opts.env ?? process.env;
  const platform = opts.platform ?? process.platform;
  const uid = opts.uid ?? (typeof process.getuid === "function" ? process.getuid() : 0);
  const r = new StepRunner({
    dryRun: opts.dryRun === true,
    out: opts.out ?? ((l) => console.log(l)),
    ...(opts.exec ? { exec: opts.exec } : {}),
    env,
  });
  const gitEnv = {
    ...env,
    GIT_AUTHOR_NAME: COMMIT_AUTHOR.name,
    GIT_AUTHOR_EMAIL: COMMIT_AUTHOR.email,
    GIT_COMMITTER_NAME: COMMIT_AUTHOR.name,
    GIT_COMMITTER_EMAIL: COMMIT_AUTHOR.email,
  };
  const git = (args: string[], comment?: string, quiet = false) => r.run("git", ["-C", dir, ...args], { env: gitEnv, quiet, ...(comment ? { comment } : {}) });
  /** Read-only, so it runs in a dry run too — a plan that says `git mv` where a plain move is coming is a plan that lied. */
  const tracked = async (rel: string): Promise<boolean> => {
    const out = await r.exec("git", ["-C", dir, "ls-files", "--", rel], { env });
    return out.code === 0 && out.stdout.trim() !== "";
  };

  const warnings: string[] = [];
  const result: MigrateLayoutResult = {
    code: 0,
    layout: "unknown",
    alreadyFlat: false,
    commands: r.commands,
    moves: [],
    rows: {},
    database: false,
    gitignore: "unchanged",
    manifests: [],
    env: [],
    committed: false,
    warnings,
  };

  // ---- 1. preflight -------------------------------------------------------
  r.section("preflight");
  if (!existsSync(join(dir, ".git"))) throw new StepFailed(`${dir} is not a git repository — pass --instance <dir> or set METISTRY_INSTANCE_DIR`);

  const plan = await planMigration(dir);
  result.layout = plan.layout;
  warnings.push(...plan.warnings);
  if (plan.layout === "flat") {
    result.alreadyFlat = true;
    r.note(`${dir} is already on the flat layout (${INSTANCE_LAYOUT.identity} exists) — nothing to do`);
    return result;
  }
  if (plan.layout === "unknown") {
    throw new StepFailed(
      `${dir} is not an instance directory: no ${INSTANCE_LAYOUT.identity} (flat), no identity.yaml and no ${LEGACY_VAULT_DIR}/ (legacy). \`metistry init <dir>\` stamps one.`,
    );
  }
  r.note(`instance layout: legacy — the vault is ${plan.vaultDir ?? LEGACY_VAULT_DIR}/ and config sits at the root`);

  const status = await r.exec("git", ["-C", dir, "status", "--porcelain"], { env });
  const dirty = status.stdout.trim();
  if (dirty !== "") {
    const shown = dirty.split("\n").slice(0, 10).join("\n  ");
    if (opts.allowDirty !== true) {
      throw new StepFailed(
        `${dir} has uncommitted changes — refusing to move the whole tree on top of them. Commit or stash first (or pass --allow-dirty if you know what is in there):\n  ${shown}`,
      );
    }
    r.note(`--allow-dirty: ${dirty.split("\n").length} uncommitted path(s) will be carried through the move`);
  } else {
    r.note("git tree is clean");
  }

  // Nothing may be writing the instance repo while it moves. The probe is
  // the one `writeProtected` already uses — `launchctl print` is what launchd
  // itself reports, and it cannot be stale the way a marker file can. A
  // WARNING rather than a refusal: launchd can tell us a label is running,
  // but not which instance directory it serves, and refusing on a second
  // instance's supervisor would be wrong.
  if (platform === "darwin") {
    let running = 0;
    for (const label of [SUPERVISOR_LABEL, RECONCILER_LABEL]) {
      const probe = await r.exec("launchctl", ["print", `gui/${uid}/${label}`], { env });
      if (probe.code === 0 && /^\s*state = running/m.test(probe.stdout)) {
        running++;
        warnings.push(
          `${label} is running. If it serves THIS instance, stop it first (\`metistry stop\`) — the reconciler is the instance repo's sole committer (D5) and will otherwise sweep this migration into commits of its own halfway through.`,
        );
      }
    }
    if (running === 0) r.note("no supervisor or reconciler job is running");
  }
  if (plan.lowercaseVaultRoots.length > 0) {
    warnings.push(
      `after this migration the vault root IS the instance root, so these lowercase entries become vault content the reconciler walks, indexes and embeds: ${plan.lowercaseVaultRoots.join(", ")}. ` +
        `Vault content is TitleCase (CLAUDE.md's one casing boundary); anything here that is not knowledge wants renaming, or moving under ${INSTANCE_LAYOUT.metistryDir}/, BEFORE you commit.`,
    );
  }
  for (const w of warnings) r.note(`warning: ${w}`);

  // ---- 2 + 3 + 4 + 5: the moves ------------------------------------------
  // `quiet`: the section's table above has already shown every one of these
  // as `from → to`, so the git invocation behind it is recorded (commands,
  // and so --json) without printing the same move twice.
  const move = async (m: LayoutMove) => {
    if (m.to === "") {
      if (r.action(`remove ${m.from}`, { quiet: true })) await rm(join(dir, m.from), { recursive: true, force: true });
      return;
    }
    if (m.via === "merge") {
      for (const entry of await entriesOf(join(dir, m.from))) {
        if (NOISE.has(entry)) continue;
        await move({ from: `${m.from}/${entry}`, to: `${m.to}/${entry}` });
      }
      if (r.action(`remove the emptied ${m.from}`, { quiet: true })) await rm(join(dir, m.from), { recursive: true, force: true });
      return;
    }
    if (m.via === "rename") {
      // same name, different case: macOS would move the directory inside itself
      const temp = `${m.to}${TEMP_SUFFIX}`;
      r.note(`${m.from} and ${m.to} are the same directory on a case-insensitive filesystem — renaming through ${temp}`);
      if (await tracked(m.from)) {
        await git(["mv", m.from, temp], undefined, true);
        await git(["mv", temp, m.to], undefined, true);
      } else if (r.action(`move ${m.from} → ${temp} → ${m.to}`, { quiet: true })) {
        await rename(join(dir, m.from), join(dir, temp));
        await rename(join(dir, temp), join(dir, m.to));
      }
      return;
    }
    if (await tracked(m.from)) await git(["mv", m.from, m.to], undefined, true);
    else if (r.action(`move ${m.from} → ${m.to}`, { quiet: true })) await rename(join(dir, m.from), join(dir, m.to));
  };

  // What this section moves, as one table, before the commands that do it:
  // a list of twenty `git mv` lines is a log, not an answer to "what is
  // about to happen to my vault" (docs/ops/cli-style.md).
  const section = (title: string, list: LayoutMove[]) => {
    r.section(title);
    if (list.length === 0) r.note("nothing to move");
    else r.table(["from", "to"], list.map((m) => [m.from, `${r.ui.icon("arrow")} ${m.to === "" ? r.ui.dim("removed") : m.to}${m.via ? r.ui.dim(`  (${m.via})`) : ""}`]));
    return list;
  };

  const underMetistry = plan.moves.filter((m) => m.to.startsWith(`${INSTANCE_LAYOUT.metistryDir}/`));
  const inbox = plan.moves.filter((m) => !m.from.includes("/") && m.to === INSTANCE_LAYOUT.inboxDir);
  const vault = plan.moves.filter((m) => m.from.includes("/"));

  if (underMetistry.length > 0 && !existsSync(join(dir, INSTANCE_LAYOUT.metistryDir))) {
    r.section(`${INSTANCE_LAYOUT.metistryDir}/`);
    if (r.action(`mkdir ${INSTANCE_LAYOUT.metistryDir}`)) await mkdir(join(dir, INSTANCE_LAYOUT.metistryDir), { recursive: true });
  }
  for (const m of section(`${INSTANCE_LAYOUT.metistryDir}/ — config and derived state`, underMetistry)) await move(m);
  for (const m of section(`${INSTANCE_LAYOUT.inboxDir}/ — the pre-#156 root inbox`, inbox)) await move(m);
  for (const m of section(`the vault — ${plan.vaultDir ?? LEGACY_VAULT_DIR}/ to the instance root`, vault)) await move(m);
  result.moves = plan.moves;

  if (plan.removeVaultDir) {
    const left = r.dryRun ? [] : (await entriesOf(join(dir, plan.removeVaultDir))).filter((e) => !NOISE.has(e));
    if (left.length > 0) throw new StepFailed(`${plan.removeVaultDir}/ is not empty after the move (${left.join(", ")}) — nothing was removed; move or remove them and re-run`);
    if (r.action(`remove the empty ${plan.removeVaultDir}/`)) {
      await rm(join(dir, plan.removeVaultDir, ".DS_Store"), { force: true });
      await rmdir(join(dir, plan.removeVaultDir)).catch(() => {});
    }
  }

  // ---- 6. manifests -------------------------------------------------------
  //
  // Reads from wherever the files are RIGHT NOW: after the moves above they
  // are under `.metistry/`, but a dry run has moved nothing, so the legacy
  // root copy is what there is to read. Same seam the `.env` step uses.
  r.section("manifests — crew scopes and target allow-lists");
  for (const bare of ["agents", "routines", "targets", "extensions"]) {
    const moved = metistryPath(dir, bare);
    const base = existsSync(moved) ? moved : join(dir, bare);
    const shown = existsSync(moved) ? `${INSTANCE_LAYOUT.metistryDir}/${bare}` : bare;
    if (!existsSync(base)) continue;
    for (const rel of await manifestsUnder(base)) {
      const file = join(base, ...rel.split("/"));
      const before = await readFile(file, "utf8");
      const rewritten = rewriteManifestAreas(before);
      for (const w of rewritten.warnings) warnings.push(`${shown}/${rel}: ${w}`);
      if (rewritten.changed.length === 0) continue;
      result.manifests.push({ file: `${shown}/${rel}`, changed: rewritten.changed });
      r.note(`${shown}/${rel}: ${rewritten.changed.join(", ")}`);
      await r.write(file, rewritten.text, "the same document with the vault prefixes dropped — comments, key order and the prompt body untouched");
    }
  }
  if (result.manifests.length === 0) r.note("no crew scope or target allow-list names a legacy vault prefix");
  else
    r.note(
      `${result.manifests.length} manifest(s) rewritten — without this the console's next crew sync (METISTRY_CREWS_SYNC_S) would write the legacy scope straight back over the grant the database step just migrated.`,
    );

  // ---- 7. .gitignore ------------------------------------------------------
  r.section(".gitignore");
  const ignorePath = join(dir, ".gitignore");
  const before = existsSync(ignorePath) ? await readFile(ignorePath, "utf8") : "";
  const after = rewriteGitignore(before);
  if (after !== before) {
    result.gitignore = "updated";
    await r.write(ignorePath, after, "core's INSTANCE_GITIGNORE_LINES, with every line this instance added kept");
  } else {
    r.note("already the flat layout's set");
  }

  // ---- 8. the database ----------------------------------------------------
  r.section("database — the Knowledge/ prefix drops out of every stored path");
  const session = await (opts.openSession ?? openMigrationSession)(env);
  result.database = session !== null;
  if (!session) {
    r.note(
      `no database configured (METISTRY_DB_PASSWORD unset) — ${DB_REWRITES.length} rewrite(s) skipped, row counts unknown. Re-run with the install's environment (\`--instance <dir>\` picks up ${INSTANCE_LAYOUT.stateDir}/.env) to rewrite them:`,
    );
    for (const w of DB_REWRITES) r.note(`  ${w.name}`);
  } else {
    try {
      if (r.dryRun) {
        for (const w of DB_REWRITES) {
          const res = (await session.query(w.count)) as { rows: { n?: number }[] };
          const n = res.rows[0]?.n ?? 0;
          result.rows[w.name] = n;
          r.note(`${w.name}: ${n} row(s) would be rewritten`);
        }
      } else {
        await session.query("BEGIN");
        try {
          for (const w of DB_REWRITES) {
            if (!r.action(w.update.replace(/\s+/g, " ").slice(0, 160))) continue;
            const res = (await session.query(w.update)) as { rowCount?: number | null };
            const n = res.rowCount ?? 0;
            result.rows[w.name] = n;
            r.note(`${w.name}: ${n} row(s)`);
          }
          await session.query("COMMIT");
        } catch (err) {
          await session.query("ROLLBACK").catch(() => {});
          const e = err as { code?: string; message?: string };
          throw new StepFailed(
            e.code === "23505"
              ? `two rows would end up at the same path once ${LEGACY_VAULT_DIR}/ is stripped — nothing was rewritten (the transaction rolled back). Resolve the duplicate by hand, then re-run.`
              : `rewriting stored paths failed: ${e.message ?? String(err)} — nothing was rewritten (the transaction rolled back)`,
          );
        }
      }
    } finally {
      await session.end().catch(() => {});
    }
  }

  // ---- 9. state/.env ------------------------------------------------------
  r.section(`${INSTANCE_LAYOUT.stateDir}/.env`);
  const envFile = join(dir, ...INSTANCE_LAYOUT.stateDir.split("/"), ".env");
  const envExists = existsSync(envFile) || (r.dryRun && existsSync(join(dir, STATE_MOVE, ".env")));
  if (!envExists) {
    r.note(`no .env (this instance keeps its environment elsewhere, or has none yet) — nothing to rewrite`);
  } else {
    const source = existsSync(envFile) ? envFile : join(dir, STATE_MOVE, ".env");
    const rewritten = rewriteEnvFile(await readFile(source, "utf8"), dir);
    warnings.push(...rewritten.warnings);
    result.env = rewritten.changed;
    for (const c of rewritten.changed) r.note(`${c.key}: ${c.from} → ${c.to}`);
    for (const w of rewritten.warnings) r.note(`warning: ${w}`);
    if (rewritten.changed.length === 0) r.note("no METISTRY_* value spells a legacy path");
    else await r.write(envFile, rewritten.text, "the same file with the legacy paths rewritten");
  }
  r.note(`launchd plists under ${INSTANCE_LAYOUT.stateDir}/ are regenerated by \`metistry up\` — this verb does not edit generated files it does not own.`);

  // ---- 10. commit ----------------------------------------------------------
  r.section("commit");
  await git(["add", "-A"], "the whole tree moved; -A is the only honest scope");
  const commit = await r.run("git", ["-C", dir, "-c", "commit.gpgsign=false", "commit", "-q", "-m", MIGRATE_LAYOUT_MESSAGE], { env: gitEnv, tolerateFailure: true });
  result.committed = !r.dryRun && commit.code === 0;
  if (!r.dryRun && commit.code !== 0) {
    r.note("commit skipped (nothing staged, or the reconciler holds the index) — the reconciler sweeps the move into a `user` commit on its next cycle");
  }

  r.section("next");
  r.note("nothing was restarted. Bring the install up so every component reads the new paths:");
  r.note("  metistry up");
  r.note(`Obsidian: point the vault at ${dir} itself now — \`${INSTANCE_LAYOUT.metistryDir}/\` is dot-prefixed, so Obsidian ignores it (docs/ops/instance-layout.md).`);
  return result;
}
